/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_A_ResultRecord_H_
#define	_A_ResultRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include "RCSD.h"
#include "ResponseData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* A-ResultRecord */
typedef struct A_ResultRecord {
	OAD_t	 objDescr;
	RCSD_t	 rsd;
	ResponseData_t	 responseData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} A_ResultRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_A_ResultRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _A_ResultRecord_H_ */
#include <asn_internal.h>
