/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ActionResponseNormal_H_
#define	_ActionResponseNormal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "OmdDarDataOPTIONAL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ActionResponseNormal */
typedef struct ActionResponseNormal {
	PIID_ACD_t	 piidACD;
	OmdDarDataOPTIONAL_t	 reponse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ActionResponseNormal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActionResponseNormal;

#ifdef __cplusplus
}
#endif

#endif	/* _ActionResponseNormal_H_ */
#include <asn_internal.h>
