/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ActionThenGetResponse_H_
#define	_ActionThenGetResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OmdDarDataOPTIONAL.h"
#include "A-ResultNormal.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ActionThenGetResponse */
typedef struct ActionThenGetResponse {
	OmdDarDataOPTIONAL_t	 omdDarDataOPTIONAL;
	A_ResultNormal_t	 a_ResultNormal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ActionThenGetResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActionThenGetResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _ActionThenGetResponse_H_ */
#include <asn_internal.h>
