/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ACTION_Request_H_
#define	_ACTION_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ActionRequestNormal.h"
#include "ActionRequestNormalList.h"
#include "ActionThenGetRequestNormalList.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ACTION_Request_PR {
	ACTION_Request_PR_NOTHING,	/* No components present */
	ACTION_Request_PR_actionRequest,
	ACTION_Request_PR_actionRequestList,
	ACTION_Request_PR_actionThenGetRequestNormalList
} ACTION_Request_PR;

/* ACTION-Request */
typedef struct ACTION_Request {
	ACTION_Request_PR present;
	union ACTION_Request_u {
		ActionRequestNormal_t	 actionRequest;
		ActionRequestNormalList_t	 actionRequestList;
		ActionThenGetRequestNormalList_t	 actionThenGetRequestNormalList;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ACTION_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACTION_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _ACTION_Request_H_ */
#include <asn_internal.h>
