/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ArrayOfGetResponseNextData_H_
#define	_ArrayOfGetResponseNextData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DAR.h"
#include "ArrayOfaResultNormal.h"
#include "ArrayOfaResultRecord.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ArrayOfGetResponseNextData_PR {
	ArrayOfGetResponseNextData_PR_NOTHING,	/* No components present */
	ArrayOfGetResponseNextData_PR_errCode,
	ArrayOfGetResponseNextData_PR_arrayOfaResultNormal,
	ArrayOfGetResponseNextData_PR_arrayOfaResultRecord
} ArrayOfGetResponseNextData_PR;

/* ArrayOfGetResponseNextData */
typedef struct ArrayOfGetResponseNextData {
	ArrayOfGetResponseNextData_PR present;
	union ArrayOfGetResponseNextData_u {
		DAR_t	 errCode;
		ArrayOfaResultNormal_t	 arrayOfaResultNormal;
		ArrayOfaResultRecord_t	 arrayOfaResultRecord;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ArrayOfGetResponseNextData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArrayOfGetResponseNextData;

#ifdef __cplusplus
}
#endif

#endif	/* _ArrayOfGetResponseNextData_H_ */
#include <asn_internal.h>
