/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ArrayOfOctet_H_
#define	_ArrayOfOctet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet-string.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ArrayOfOctet */
typedef struct ArrayOfOctet {
	A_SEQUENCE_OF(Octet_string_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ArrayOfOctet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArrayOfOctet;

#ifdef __cplusplus
}
#endif

#endif	/* _ArrayOfOctet_H_ */
#include <asn_internal.h>
