/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "ArrayOfGetResponseNextData.h"

static asn_per_constraints_t asn_PER_type_ArrayOfGetResponseNextData_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ArrayOfGetResponseNextData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ArrayOfGetResponseNextData, choice.errCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DAR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"errCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ArrayOfGetResponseNextData, choice.arrayOfaResultNormal),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ArrayOfaResultNormal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"arrayOfaResultNormal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ArrayOfGetResponseNextData, choice.arrayOfaResultRecord),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ArrayOfaResultRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"arrayOfaResultRecord"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ArrayOfGetResponseNextData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* errCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* arrayOfaResultNormal */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* arrayOfaResultRecord */
};
static asn_CHOICE_specifics_t asn_SPC_ArrayOfGetResponseNextData_specs_1 = {
	sizeof(struct ArrayOfGetResponseNextData),
	offsetof(struct ArrayOfGetResponseNextData, _asn_ctx),
	offsetof(struct ArrayOfGetResponseNextData, present),
	sizeof(((struct ArrayOfGetResponseNextData *)0)->present),
	asn_MAP_ArrayOfGetResponseNextData_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ArrayOfGetResponseNextData = {
	"ArrayOfGetResponseNextData",
	"ArrayOfGetResponseNextData",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ArrayOfGetResponseNextData_constr_1,
	asn_MBR_ArrayOfGetResponseNextData_1,
	3,	/* Elements count */
	&asn_SPC_ArrayOfGetResponseNextData_specs_1	/* Additional specs */
};

