/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal_H_
#define	_ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OMD_DAR_DATAOPTION_A_ResultNormal;

/* ArrayOfOMD-DAR-DATAOPTION-A-ResultNormal */
typedef struct ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal {
	A_SEQUENCE_OF(struct OMD_DAR_DATAOPTION_A_ResultNormal) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OMD-DAR-DATAOPTION-A-ResultNormal.h"

#endif	/* _ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal_H_ */
#include <asn_internal.h>
