/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ArrayOfOmdDarDataOPTIONAL_H_
#define	_ArrayOfOmdDarDataOPTIONAL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OmdDarDataOPTIONAL;

/* ArrayOfOmdDarDataOPTIONAL */
typedef struct ArrayOfOmdDarDataOPTIONAL {
	A_SEQUENCE_OF(struct OmdDarDataOPTIONAL) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ArrayOfOmdDarDataOPTIONAL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArrayOfOmdDarDataOPTIONAL;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OmdDarDataOPTIONAL.h"

#endif	/* _ArrayOfOmdDarDataOPTIONAL_H_ */
#include <asn_internal.h>
