/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_BaudRate_H_
#define	_BaudRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BaudRate {
	BaudRate_baud300bps	= 0,
	BaudRate_baud600bps	= 1,
	BaudRate_baud1200bps	= 2,
	BaudRate_baud2400bps	= 3,
	BaudRate_baud4800bps	= 4,
	BaudRate_baud7200bps	= 5,
	BaudRate_baud9600bps	= 6,
	BaudRate_baud19200bps	= 7,
	BaudRate_baud38400bps	= 8,
	BaudRate_baud57600bps	= 9,
	BaudRate_baud115200bps	= 10,
	BaudRate_autoAjust	= 255
} e_BaudRate;

/* BaudRate */
typedef long	 BaudRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BaudRate;
asn_struct_free_f BaudRate_free;
asn_struct_print_f BaudRate_print;
asn_constr_check_f BaudRate_constraint;
ber_type_decoder_f BaudRate_decode_ber;
der_type_encoder_f BaudRate_encode_der;
xer_type_decoder_f BaudRate_decode_xer;
xer_type_encoder_f BaudRate_encode_xer;
per_type_decoder_f BaudRate_decode_uper;
per_type_encoder_f BaudRate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BaudRate_H_ */
#include <asn_internal.h>
