/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Bool_H_
#define	_Bool_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bool */
typedef BOOLEAN_t	 Bool_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Bool;
asn_struct_free_f Bool_free;
asn_struct_print_f Bool_print;
asn_constr_check_f Bool_constraint;
ber_type_decoder_f Bool_decode_ber;
der_type_encoder_f Bool_encode_der;
xer_type_decoder_f Bool_decode_xer;
xer_type_encoder_f Bool_encode_xer;
per_type_decoder_f Bool_decode_uper;
per_type_encoder_f Bool_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Bool_H_ */
#include <asn_internal.h>
