/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Client_APDU_H_
#define	_Client_APDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CONNECT-Request.h"
#include "RELEASE-Request.h"
#include "GET-Request.h"
#include "SET-Request.h"
#include "ACTION-Request.h"
#include "REPORT-Response.h"
#include "PROXY-Request.h"
#include "ERROR-Response.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum appLayerSvrClient_PR {
	appLayerSvrClient_PR_NOTHING,	/* No components present */
	appLayerSvrClient_PR_connectRequest,
	appLayerSvrClient_PR_releaseRequest,
	appLayerSvrClient_PR_getRequest,
	appLayerSvrClient_PR_setRequest,
	appLayerSvrClient_PR_actionRequest,
	appLayerSvrClient_PR_reportResponse,
	appLayerSvrClient_PR_proxyRequest,
	appLayerSvrClient_PR_errorResponse
} appLayerSvrClient_PR;

/* Forward declarations */
struct TimeTag;

/* Client-APDU */
typedef struct Client_APDU {
	struct appLayerSvrClient {
		appLayerSvrClient_PR present;
		union Client_APDU__appLayerSvrClient_u {
			CONNECT_Request_t	 connectRequest;
			RELEASE_Request_t	 releaseRequest;
			GET_Request_t	 getRequest;
			SET_Request_t	 setRequest;
			ACTION_Request_t	 actionRequest;
			REPORT_Response_t	 reportResponse;
			PROXY_Request_t	 proxyRequest;
			ERROR_Response_t	 errorResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} appLayerSvrClient;
	struct TimeTag	*timeTag	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Client_APDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Client_APDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TimeTag.h"

#endif	/* _Client_APDU_H_ */
#include <asn_internal.h>
