/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "Client-APDU.h"

static asn_per_constraints_t asn_PER_type_appLayerSvrClient_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_appLayerSvrClient_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.connectRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CONNECT_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"connectRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.releaseRequest),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RELEASE_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"releaseRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.getRequest),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GET_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.setRequest),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SET_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.actionRequest),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ACTION_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"actionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.reportResponse),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_REPORT_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.proxyRequest),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PROXY_Request,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrClient, choice.errorResponse),
		(ASN_TAG_CLASS_CONTEXT | (110 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ERROR_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"errorResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_appLayerSvrClient_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* connectRequest */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* releaseRequest */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* getRequest */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 }, /* setRequest */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 4, 0, 0 }, /* actionRequest */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 5, 0, 0 }, /* reportResponse */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 6, 0, 0 }, /* proxyRequest */
    { (ASN_TAG_CLASS_CONTEXT | (110 << 2)), 7, 0, 0 } /* errorResponse */
};
static asn_CHOICE_specifics_t asn_SPC_appLayerSvrClient_specs_2 = {
	sizeof(struct appLayerSvrClient),
	offsetof(struct appLayerSvrClient, _asn_ctx),
	offsetof(struct appLayerSvrClient, present),
	sizeof(((struct appLayerSvrClient *)0)->present),
	asn_MAP_appLayerSvrClient_tag2el_2,
	8,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_appLayerSvrClient_2 = {
	"appLayerSvrClient",
	"appLayerSvrClient",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_appLayerSvrClient_constr_2,
	asn_MBR_appLayerSvrClient_2,
	8,	/* Elements count */
	&asn_SPC_appLayerSvrClient_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Client_APDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Client_APDU, appLayerSvrClient),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_appLayerSvrClient_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"appLayerSvrClient"
		},
	{ ATF_POINTER, 1, offsetof(struct Client_APDU, timeTag),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TimeTag,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeTag"
		},
};
static const int asn_MAP_Client_APDU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_Client_APDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Client_APDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* timeTag */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* connectRequest */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* releaseRequest */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 }, /* getRequest */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* setRequest */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 0, 0, 0 }, /* actionRequest */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 }, /* reportResponse */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 0, 0, 0 }, /* proxyRequest */
    { (ASN_TAG_CLASS_CONTEXT | (110 << 2)), 0, 0, 0 } /* errorResponse */
};
static asn_SEQUENCE_specifics_t asn_SPC_Client_APDU_specs_1 = {
	sizeof(struct Client_APDU),
	offsetof(struct Client_APDU, _asn_ctx),
	asn_MAP_Client_APDU_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_Client_APDU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Client_APDU = {
	"Client-APDU",
	"Client-APDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Client_APDU_tags_1,
	sizeof(asn_DEF_Client_APDU_tags_1)
		/sizeof(asn_DEF_Client_APDU_tags_1[0]), /* 1 */
	asn_DEF_Client_APDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Client_APDU_tags_1)
		/sizeof(asn_DEF_Client_APDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Client_APDU_1,
	2,	/* Elements count */
	&asn_SPC_Client_APDU_specs_1	/* Additional specs */
};

