/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "COMDCB.h"

static asn_TYPE_member_t asn_MBR_COMDCB_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct COMDCB, baudrate),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_BaudRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"baudrate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COMDCB, parity),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Parity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"parity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COMDCB, databits),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_DataBits,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"databits"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COMDCB, stopbits),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_StopBits,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"stopbits"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct COMDCB, flowctl),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_FlowCtl,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"flowctl"
		},
};
static const ber_tlv_tag_t asn_DEF_COMDCB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_COMDCB_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 4 }, /* baudrate */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, -1, 3 }, /* parity */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, -2, 2 }, /* databits */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 3, -3, 1 }, /* stopbits */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 4, -4, 0 } /* flowctl */
};
static asn_SEQUENCE_specifics_t asn_SPC_COMDCB_specs_1 = {
	sizeof(struct COMDCB),
	offsetof(struct COMDCB, _asn_ctx),
	asn_MAP_COMDCB_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_COMDCB = {
	"COMDCB",
	"COMDCB",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_COMDCB_tags_1,
	sizeof(asn_DEF_COMDCB_tags_1)
		/sizeof(asn_DEF_COMDCB_tags_1[0]), /* 1 */
	asn_DEF_COMDCB_tags_1,	/* Same as above */
	sizeof(asn_DEF_COMDCB_tags_1)
		/sizeof(asn_DEF_COMDCB_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_COMDCB_1,
	5,	/* Elements count */
	&asn_SPC_COMDCB_specs_1	/* Additional specs */
};

