/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "CONNECT-Response.h"

static asn_TYPE_member_t asn_MBR_CONNECT_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, piidACD),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID_ACD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"piidACD"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, factoryVer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FactoryVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"factoryVer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, negotiateAppProtocolVer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"negotiateAppProtocolVer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, negotiateProtocolConsistency),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_ProtocolConformance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"negotiateProtocolConsistency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, negotiateFuncConsistency),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_FunctionConformance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"negotiateFuncConsistency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, svrMaxSend),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"svrMaxSend"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, svrMaxRecv),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"svrMaxRecv"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, svrMaxWindow),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"svrMaxWindow"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, svrMaxApdu),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"svrMaxApdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, negotiateAppLinkDelay),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_DoubleLongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"negotiateAppLinkDelay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Response, connectResponseObj),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ConnectResponseInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"connectResponseObj"
		},
};
static const ber_tlv_tag_t asn_DEF_CONNECT_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CONNECT_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 6 }, /* piidACD */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 5 }, /* negotiateAppProtocolVer */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -2, 4 }, /* svrMaxSend */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -3, 3 }, /* svrMaxRecv */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -4, 2 }, /* svrMaxWindow */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -5, 1 }, /* svrMaxApdu */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 9, -6, 0 }, /* negotiateAppLinkDelay */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, 0, 1 }, /* negotiateProtocolConsistency */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 4, -1, 0 }, /* negotiateFuncConsistency */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* factoryVer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -1, 0 } /* connectResponseObj */
};
static asn_SEQUENCE_specifics_t asn_SPC_CONNECT_Response_specs_1 = {
	sizeof(struct CONNECT_Response),
	offsetof(struct CONNECT_Response, _asn_ctx),
	asn_MAP_CONNECT_Response_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CONNECT_Response = {
	"CONNECT-Response",
	"CONNECT-Response",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CONNECT_Response_tags_1,
	sizeof(asn_DEF_CONNECT_Response_tags_1)
		/sizeof(asn_DEF_CONNECT_Response_tags_1[0]), /* 1 */
	asn_DEF_CONNECT_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_CONNECT_Response_tags_1)
		/sizeof(asn_DEF_CONNECT_Response_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CONNECT_Response_1,
	11,	/* Elements count */
	&asn_SPC_CONNECT_Response_specs_1	/* Additional specs */
};

