/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "CONNECT-Request.h"

static asn_TYPE_member_t asn_MBR_CONNECT_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, prioInvID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"prioInvID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, expectAppProtocolVer),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"expectAppProtocolVer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, expectProtocolConsistency),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_ProtocolConformance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"expectProtocolConsistency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, expectFuncConsistency),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_FunctionConformance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"expectFuncConsistency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, clientMaxSend),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"clientMaxSend"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, clientMaxRecv),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"clientMaxRecv"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, clientMaxWindow),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"clientMaxWindow"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, clientMaxApdu),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"clientMaxApdu"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, expectAppLinkDelay),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_DoubleLongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"expectAppLinkDelay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CONNECT_Request, authRequestObj),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ConnectMechanismInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"authRequestObj"
		},
};
static const ber_tlv_tag_t asn_DEF_CONNECT_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CONNECT_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 6 }, /* prioInvID */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 5 }, /* expectAppProtocolVer */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 4 }, /* clientMaxSend */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -3, 3 }, /* clientMaxRecv */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -4, 2 }, /* clientMaxWindow */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -5, 1 }, /* clientMaxApdu */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -6, 0 }, /* expectAppLinkDelay */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 1 }, /* expectProtocolConsistency */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, -1, 0 }, /* expectFuncConsistency */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 9, 0, 0 }, /* publicConnection */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 9, 0, 0 }, /* pwdSec */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 9, 0, 0 }, /* symmSec */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 9, 0, 0 } /* sigSec */
};
static asn_SEQUENCE_specifics_t asn_SPC_CONNECT_Request_specs_1 = {
	sizeof(struct CONNECT_Request),
	offsetof(struct CONNECT_Request, _asn_ctx),
	asn_MAP_CONNECT_Request_tag2el_1,
	13,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CONNECT_Request = {
	"CONNECT-Request",
	"CONNECT-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CONNECT_Request_tags_1,
	sizeof(asn_DEF_CONNECT_Request_tags_1)
		/sizeof(asn_DEF_CONNECT_Request_tags_1[0]), /* 1 */
	asn_DEF_CONNECT_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_CONNECT_Request_tags_1)
		/sizeof(asn_DEF_CONNECT_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CONNECT_Request_1,
	10,	/* Elements count */
	&asn_SPC_CONNECT_Request_specs_1	/* Additional specs */
};

