/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_CONNECT_Response_H_
#define	_CONNECT_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "FactoryVersion.h"
#include "LongUnsigned.h"
#include "ProtocolConformance.h"
#include "FunctionConformance.h"
#include "Unsigned.h"
#include "DoubleLongUnsigned.h"
#include "ConnectResponseInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CONNECT-Response */
typedef struct CONNECT_Response {
	PIID_ACD_t	 piidACD;
	FactoryVersion_t	 factoryVer;
	LongUnsigned_t	 negotiateAppProtocolVer;
	ProtocolConformance_t	 negotiateProtocolConsistency;
	FunctionConformance_t	 negotiateFuncConsistency;
	LongUnsigned_t	 svrMaxSend;
	LongUnsigned_t	 svrMaxRecv;
	Unsigned_t	 svrMaxWindow;
	LongUnsigned_t	 svrMaxApdu;
	DoubleLongUnsigned_t	 negotiateAppLinkDelay;
	ConnectResponseInfo_t	 connectResponseObj;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CONNECT_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CONNECT_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _CONNECT_Response_H_ */
#include <asn_internal.h>
