/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "ConnectMechanismInfo.h"

static asn_per_constraints_t asn_PER_type_ConnectMechanismInfo_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ConnectMechanismInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectMechanismInfo, choice.publicConnection),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NullSecurity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"publicConnection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectMechanismInfo, choice.pwdSec),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PasswordSecurity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pwdSec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectMechanismInfo, choice.symmSec),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SymmetrySecurity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"symmSec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectMechanismInfo, choice.sigSec),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SignatureSecurity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sigSec"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ConnectMechanismInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* publicConnection */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pwdSec */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* symmSec */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* sigSec */
};
static asn_CHOICE_specifics_t asn_SPC_ConnectMechanismInfo_specs_1 = {
	sizeof(struct ConnectMechanismInfo),
	offsetof(struct ConnectMechanismInfo, _asn_ctx),
	offsetof(struct ConnectMechanismInfo, present),
	sizeof(((struct ConnectMechanismInfo *)0)->present),
	asn_MAP_ConnectMechanismInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ConnectMechanismInfo = {
	"ConnectMechanismInfo",
	"ConnectMechanismInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_ConnectMechanismInfo_constr_1,
	asn_MBR_ConnectMechanismInfo_1,
	4,	/* Elements count */
	&asn_SPC_ConnectMechanismInfo_specs_1	/* Additional specs */
};

