/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ConnectMechanismInfo_H_
#define	_ConnectMechanismInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NullSecurity.h"
#include "PasswordSecurity.h"
#include "SymmetrySecurity.h"
#include "SignatureSecurity.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConnectMechanismInfo_PR {
	ConnectMechanismInfo_PR_NOTHING,	/* No components present */
	ConnectMechanismInfo_PR_publicConnection,
	ConnectMechanismInfo_PR_pwdSec,
	ConnectMechanismInfo_PR_symmSec,
	ConnectMechanismInfo_PR_sigSec
} ConnectMechanismInfo_PR;

/* ConnectMechanismInfo */
typedef struct ConnectMechanismInfo {
	ConnectMechanismInfo_PR present;
	union ConnectMechanismInfo_u {
		NullSecurity_t	 publicConnection;
		PasswordSecurity_t	 pwdSec;
		SymmetrySecurity_t	 symmSec;
		SignatureSecurity_t	 sigSec;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectMechanismInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectMechanismInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectMechanismInfo_H_ */
#include <asn_internal.h>
