/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_CSD_H_
#define	_CSD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include "ROAD.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CSD_PR {
	CSD_PR_NOTHING,	/* No components present */
	CSD_PR_oad,
	CSD_PR_road
} CSD_PR;

/* CSD */
typedef struct CSD {
	CSD_PR present;
	union CSD_u {
		OAD_t	 oad;
		ROAD_t	 road;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSD;

#ifdef __cplusplus
}
#endif

#endif	/* _CSD_H_ */
#include <asn_internal.h>
