/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_DataChkInfo_H_
#define	_DataChkInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MAC.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataChkInfo_PR {
	DataChkInfo_PR_NOTHING,	/* No components present */
	DataChkInfo_PR_mac
} DataChkInfo_PR;

/* DataChkInfo */
typedef struct DataChkInfo {
	DataChkInfo_PR present;
	union DataChkInfo_u {
		MAC_t	 mac;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataChkInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataChkInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _DataChkInfo_H_ */
#include <asn_internal.h>
