/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "Data.h"

static asn_per_constraints_t asn_PER_type_Data_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  39 }	/* (0..39) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_array_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_array_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_array_specs_3 = {
	sizeof(struct array),
	offsetof(struct array, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_array_3 = {
	"array",
	"array",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_array_tags_3,
	sizeof(asn_DEF_array_tags_3)
		/sizeof(asn_DEF_array_tags_3[0]), /* 2 */
	asn_DEF_array_tags_3,	/* Same as above */
	sizeof(asn_DEF_array_tags_3)
		/sizeof(asn_DEF_array_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_array_3,
	1,	/* Single element */
	&asn_SPC_array_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_structure_5[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_structure_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_structure_specs_5 = {
	sizeof(struct structure),
	offsetof(struct structure, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_structure_5 = {
	"structure",
	"structure",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_structure_tags_5,
	sizeof(asn_DEF_structure_tags_5)
		/sizeof(asn_DEF_structure_tags_5[0]), /* 2 */
	asn_DEF_structure_tags_5,	/* Same as above */
	sizeof(asn_DEF_structure_tags_5)
		/sizeof(asn_DEF_structure_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_structure_5,
	1,	/* Single element */
	&asn_SPC_structure_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.null),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"null"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_array_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"array"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_structure_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Bool),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Bool,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bool"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.bitString),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Bit_string,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bitString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.doubleLong),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DoubleLong,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"doubleLong"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.doubleLongunsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DoubleLongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"doubleLongunsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.octetString),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Octet_string,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"octetString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.visibleString),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"visibleString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.utf8String),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"utf8String"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Integer8s,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Long),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Long,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"long"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.longunsigned),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"longunsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.long64),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Long64,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"long64"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.long64Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Long64Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"long64Unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Enum),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Enum,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"enum"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.float32),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Float32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"float32"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.float64),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Float64,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"float64"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.dateTime),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Date_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dateTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.date),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Date,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"date"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.time),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.date_Time_s),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Date_Time_S,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"date-Time-s"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.oi),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"oi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.oad),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"oad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.road),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ROAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"road"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.omd),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OMD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"omd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.ti),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.tsa),
		(ASN_TAG_CLASS_CONTEXT | (85 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TSA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tsa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.mac),
		(ASN_TAG_CLASS_CONTEXT | (86 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MAC,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.rn),
		(ASN_TAG_CLASS_CONTEXT | (87 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rn"
		},
	{ ATF_POINTER, 0, offsetof(struct Data, choice.region),
		(ASN_TAG_CLASS_CONTEXT | (88 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Region,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"region"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.scalerUnit),
		(ASN_TAG_CLASS_CONTEXT | (89 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ScalerUnit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"scalerUnit"
		},
	{ ATF_POINTER, 0, offsetof(struct Data, choice.rsd),
		(ASN_TAG_CLASS_CONTEXT | (90 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RSD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rsd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.csd),
		(ASN_TAG_CLASS_CONTEXT | (91 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CSD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csd"
		},
	{ ATF_POINTER, 0, offsetof(struct Data, choice.ms),
		(ASN_TAG_CLASS_CONTEXT | (92 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MS,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ms"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.sid),
		(ASN_TAG_CLASS_CONTEXT | (93 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.sidMac),
		(ASN_TAG_CLASS_CONTEXT | (94 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SID_MAC,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sidMac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.comdcb),
		(ASN_TAG_CLASS_CONTEXT | (95 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_COMDCB,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"comdcb"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.rcsd),
		(ASN_TAG_CLASS_CONTEXT | (96 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RCSD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rcsd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* null */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* bool */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* doubleLong */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* doubleLongunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* utf8String */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 10, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 11, 0, 0 }, /* long */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 12, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 13, 0, 0 }, /* longunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 14, 0, 0 }, /* long64 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 15, 0, 0 }, /* long64Unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 16, 0, 0 }, /* enum */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 17, 0, 0 }, /* float32 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 18, 0, 0 }, /* float64 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 19, 0, 0 }, /* dateTime */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 20, 0, 0 }, /* date */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 21, 0, 0 }, /* time */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 22, 0, 0 }, /* date-Time-s */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 23, 0, 0 }, /* oi */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 24, 0, 0 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 25, 0, 0 }, /* road */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 26, 0, 0 }, /* omd */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 27, 0, 0 }, /* ti */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 28, 0, 0 }, /* tsa */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 29, 0, 0 }, /* mac */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 30, 0, 0 }, /* rn */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 31, 0, 0 }, /* region */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 32, 0, 0 }, /* scalerUnit */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 33, 0, 0 }, /* rsd */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 34, 0, 0 }, /* csd */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 35, 0, 0 }, /* ms */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 36, 0, 0 }, /* sid */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 37, 0, 0 }, /* sidMac */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 38, 0, 0 }, /* comdcb */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 39, 0, 0 } /* rcsd */
};
static asn_CHOICE_specifics_t asn_SPC_Data_specs_1 = {
	sizeof(struct Data),
	offsetof(struct Data, _asn_ctx),
	offsetof(struct Data, present),
	sizeof(((struct Data *)0)->present),
	asn_MAP_Data_tag2el_1,
	40,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Data = {
	"Data",
	"Data",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Data_constr_1,
	asn_MBR_Data_1,
	40,	/* Elements count */
	&asn_SPC_Data_specs_1	/* Additional specs */
};

