/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Data_H_
#define	_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Bool.h"
#include "Bit-string.h"
#include "DoubleLong.h"
#include "DoubleLongUnsigned.h"
#include "Octet-string.h"
#include <VisibleString.h>
#include <UTF8String.h>
#include "Integer8s.h"
#include "Long.h"
#include "Unsigned.h"
#include "LongUnsigned.h"
#include "Long64.h"
#include "Long64Unsigned.h"
#include "Enum.h"
#include "Float32.h"
#include "Float64.h"
#include "Date-Time.h"
#include "Date.h"
#include "Time.h"
#include "Date-Time-S.h"
#include "OI.h"
#include "OAD.h"
#include "ROAD.h"
#include "OMD.h"
#include "TI.h"
#include "TSA.h"
#include "MAC.h"
#include "RN.h"
#include "ScalerUnit.h"
#include "CSD.h"
#include "SID.h"
#include "SID-MAC.h"
#include "COMDCB.h"
#include "RCSD.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Data_PR {
	Data_PR_NOTHING,	/* No components present */
	Data_PR_null,
	Data_PR_array,
	Data_PR_structure,
	Data_PR_bool,
	Data_PR_bitString,
	Data_PR_doubleLong,
	Data_PR_doubleLongunsigned,
	Data_PR_octetString,
	Data_PR_visibleString,
	Data_PR_utf8String,
	Data_PR_integer,
	Data_PR_long,
	Data_PR_unsigned,
	Data_PR_longunsigned,
	Data_PR_long64,
	Data_PR_long64Unsigned,
	Data_PR_enum,
	Data_PR_float32,
	Data_PR_float64,
	Data_PR_dateTime,
	Data_PR_date,
	Data_PR_time,
	Data_PR_date_Time_s,
	Data_PR_oi,
	Data_PR_oad,
	Data_PR_road,
	Data_PR_omd,
	Data_PR_ti,
	Data_PR_tsa,
	Data_PR_mac,
	Data_PR_rn,
	Data_PR_region,
	Data_PR_scalerUnit,
	Data_PR_rsd,
	Data_PR_csd,
	Data_PR_ms,
	Data_PR_sid,
	Data_PR_sidMac,
	Data_PR_comdcb,
	Data_PR_rcsd
} Data_PR;

/* Forward declarations */
struct Region;
struct RSD;
struct MS;
struct Data;

/* Data */
typedef struct Data {
	Data_PR present;
	union Data_u {
		NULL_t	 null;
		struct array {
			A_SEQUENCE_OF(struct Data) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} array;
		struct structure {
			A_SEQUENCE_OF(struct Data) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} structure;
		Bool_t	 Bool;
		Bit_string_t	 bitString;
		DoubleLong_t	 doubleLong;
		DoubleLongUnsigned_t	 doubleLongunsigned;
		Octet_string_t	 octetString;
		VisibleString_t	 visibleString;
		UTF8String_t	 utf8String;
		Integer8s_t	 integer;
		Long_t	 Long;
		Unsigned_t	 Unsigned;
		LongUnsigned_t	 longunsigned;
		Long64_t	 long64;
		Long64Unsigned_t	 long64Unsigned;
		Enum_t	 Enum;
		Float32_t	 float32;
		Float64_t	 float64;
		Date_Time_t	 dateTime;
		Date_t	 date;
		Time_t	 time;
		Date_Time_S_t	 date_Time_s;
		OI_t	 oi;
		OAD_t	 oad;
		ROAD_t	 road;
		OMD_t	 omd;
		TI_t	 ti;
		TSA_t	 tsa;
		MAC_t	 mac;
		RN_t	 rn;
		struct Region	*region;
		ScalerUnit_t	 scalerUnit;
		struct RSD	*rsd;
		CSD_t	 csd;
		struct MS	*ms;
		SID_t	 sid;
		SID_MAC_t	 sidMac;
		COMDCB_t	 comdcb;
		RCSD_t	 rcsd;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Region.h"
#include "RSD.h"
#include "MS.h"
#include "Data.h"

#endif	/* _Data_H_ */
#include <asn_internal.h>
