/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_DataBits_H_
#define	_DataBits_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataBits {
	DataBits_databit5	= 5,
	DataBits_databit6	= 6,
	DataBits_databit7	= 7,
	DataBits_databit8	= 8
} e_DataBits;

/* DataBits */
typedef long	 DataBits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataBits;
asn_struct_free_f DataBits_free;
asn_struct_print_f DataBits_print;
asn_constr_check_f DataBits_constraint;
ber_type_decoder_f DataBits_decode_ber;
der_type_encoder_f DataBits_encode_der;
xer_type_decoder_f DataBits_decode_xer;
xer_type_encoder_f DataBits_encode_xer;
per_type_decoder_f DataBits_decode_uper;
per_type_encoder_f DataBits_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DataBits_H_ */
#include <asn_internal.h>
