/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "Date-Time.h"

static asn_TYPE_member_t asn_MBR_Date_Time_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, year),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"year"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, month),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"month"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, dayOfMonth),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dayOfMonth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, dayOfWeek),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dayOfWeek"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, hour),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hour"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, minute),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"minute"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, second),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"second"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Date_Time, milliseconds),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"milliseconds"
		},
};
static const ber_tlv_tag_t asn_DEF_Date_Time_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Date_Time_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 7 }, /* year */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 6 }, /* month */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 5 }, /* dayOfMonth */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -3, 4 }, /* dayOfWeek */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -4, 3 }, /* hour */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -5, 2 }, /* minute */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -6, 1 }, /* second */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -7, 0 } /* milliseconds */
};
static asn_SEQUENCE_specifics_t asn_SPC_Date_Time_specs_1 = {
	sizeof(struct Date_Time),
	offsetof(struct Date_Time, _asn_ctx),
	asn_MAP_Date_Time_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Date_Time = {
	"Date-Time",
	"Date-Time",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Date_Time_tags_1,
	sizeof(asn_DEF_Date_Time_tags_1)
		/sizeof(asn_DEF_Date_Time_tags_1[0]), /* 1 */
	asn_DEF_Date_Time_tags_1,	/* Same as above */
	sizeof(asn_DEF_Date_Time_tags_1)
		/sizeof(asn_DEF_Date_Time_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Date_Time_1,
	8,	/* Elements count */
	&asn_SPC_Date_Time_specs_1	/* Additional specs */
};

