/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_DoubleLongUnsigned_H_
#define	_DoubleLongUnsigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DoubleLongUnsigned */
typedef unsigned long	 DoubleLongUnsigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DoubleLongUnsigned;
asn_struct_free_f DoubleLongUnsigned_free;
asn_struct_print_f DoubleLongUnsigned_print;
asn_constr_check_f DoubleLongUnsigned_constraint;
ber_type_decoder_f DoubleLongUnsigned_decode_ber;
der_type_encoder_f DoubleLongUnsigned_encode_der;
xer_type_decoder_f DoubleLongUnsigned_decode_xer;
xer_type_encoder_f DoubleLongUnsigned_encode_xer;
per_type_decoder_f DoubleLongUnsigned_decode_uper;
per_type_encoder_f DoubleLongUnsigned_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DoubleLongUnsigned_H_ */
#include <asn_internal.h>
