/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_DoubleLong_H_
#define	_DoubleLong_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DoubleLong */
typedef long	 DoubleLong_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DoubleLong;
asn_struct_free_f DoubleLong_free;
asn_struct_print_f DoubleLong_print;
asn_constr_check_f DoubleLong_constraint;
ber_type_decoder_f DoubleLong_decode_ber;
der_type_encoder_f DoubleLong_encode_der;
xer_type_decoder_f DoubleLong_decode_xer;
xer_type_encoder_f DoubleLong_encode_xer;
per_type_decoder_f DoubleLong_decode_uper;
per_type_encoder_f DoubleLong_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DoubleLong_H_ */
#include <asn_internal.h>
