/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ErrorResponseType_H_
#define	_ErrorResponseType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ErrorResponseType {
	ErrorResponseType_apduErr	= 1,
	ErrorResponseType_svrUnSpt	= 2,
	ErrorResponseType_other	= 255
} e_ErrorResponseType;

/* ErrorResponseType */
typedef long	 ErrorResponseType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ErrorResponseType;
asn_struct_free_f ErrorResponseType_free;
asn_struct_print_f ErrorResponseType_print;
asn_constr_check_f ErrorResponseType_constraint;
ber_type_decoder_f ErrorResponseType_decode_ber;
der_type_encoder_f ErrorResponseType_encode_der;
xer_type_decoder_f ErrorResponseType_decode_xer;
xer_type_encoder_f ErrorResponseType_encode_xer;
per_type_decoder_f ErrorResponseType_decode_uper;
per_type_encoder_f ErrorResponseType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ErrorResponseType_H_ */
#include <asn_internal.h>
