/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_FactoryVersion_H_
#define	_FactoryVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FactoryVersion */
typedef struct FactoryVersion {
	VisibleString_t	 vendorCode;
	VisibleString_t	 softVerCode;
	VisibleString_t	 softverDate;
	VisibleString_t	 hardVerCode;
	VisibleString_t	 hardVerDate;
	VisibleString_t	 vendorExtInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FactoryVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FactoryVersion;

#ifdef __cplusplus
}
#endif

#endif	/* _FactoryVersion_H_ */
#include <asn_internal.h>
