/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Float32_H_
#define	_Float32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Float32 */
typedef OCTET_STRING_t	 Float32_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Float32;
asn_struct_free_f Float32_free;
asn_struct_print_f Float32_print;
asn_constr_check_f Float32_constraint;
ber_type_decoder_f Float32_decode_ber;
der_type_encoder_f Float32_encode_der;
xer_type_decoder_f Float32_decode_xer;
xer_type_encoder_f Float32_encode_xer;
per_type_decoder_f Float32_decode_uper;
per_type_encoder_f Float32_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Float32_H_ */
#include <asn_internal.h>
