/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_FlowCtl_H_
#define	_FlowCtl_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FlowCtl {
	FlowCtl_no	= 0,
	FlowCtl_hard	= 1,
	FlowCtl_soft	= 2
} e_FlowCtl;

/* FlowCtl */
typedef long	 FlowCtl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FlowCtl;
asn_struct_free_f FlowCtl_free;
asn_struct_print_f FlowCtl_print;
asn_constr_check_f FlowCtl_constraint;
ber_type_decoder_f FlowCtl_decode_ber;
der_type_encoder_f FlowCtl_encode_der;
xer_type_decoder_f FlowCtl_decode_xer;
xer_type_encoder_f FlowCtl_encode_xer;
per_type_decoder_f FlowCtl_decode_uper;
per_type_encoder_f FlowCtl_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FlowCtl_H_ */
#include <asn_internal.h>
