/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_FollowReport_H_
#define	_FollowReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ArrayOfaResultNormal.h"
#include "ArrayOfaResultRecord.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FollowReport_PR {
	FollowReport_PR_NOTHING,	/* No components present */
	FollowReport_PR_arrayOfObjAttrData,
	FollowReport_PR_arrayOfRecAttrData
} FollowReport_PR;

/* FollowReport */
typedef struct FollowReport {
	FollowReport_PR present;
	union FollowReport_u {
		ArrayOfaResultNormal_t	 arrayOfObjAttrData;
		ArrayOfaResultRecord_t	 arrayOfRecAttrData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FollowReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FollowReport;

#ifdef __cplusplus
}
#endif

#endif	/* _FollowReport_H_ */
#include <asn_internal.h>
