/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_FunctionConformance_H_
#define	_FunctionConformance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Bit-string.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FunctionConformance */
typedef Bit_string_t	 FunctionConformance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FunctionConformance;
asn_struct_free_f FunctionConformance_free;
asn_struct_print_f FunctionConformance_print;
asn_constr_check_f FunctionConformance_constraint;
ber_type_decoder_f FunctionConformance_decode_ber;
der_type_encoder_f FunctionConformance_encode_der;
xer_type_decoder_f FunctionConformance_decode_xer;
xer_type_encoder_f FunctionConformance_encode_xer;
per_type_decoder_f FunctionConformance_decode_uper;
per_type_encoder_f FunctionConformance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FunctionConformance_H_ */
#include <asn_internal.h>
