/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "GET-Response.h"

static asn_per_constraints_t asn_PER_type_GET_Response_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GET_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseNormal),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseNormal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseNormal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseNormalList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseNormalList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseNormalList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseRecord),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseRecordList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseRecordList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseRecordList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseNext),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseNext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseNext"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GET_Response, choice.getResponseMD5),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GetResponseMD5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponseMD5"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_GET_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* getResponseNormal */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* getResponseNormalList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* getResponseRecord */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* getResponseRecordList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* getResponseNext */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* getResponseMD5 */
};
static asn_CHOICE_specifics_t asn_SPC_GET_Response_specs_1 = {
	sizeof(struct GET_Response),
	offsetof(struct GET_Response, _asn_ctx),
	offsetof(struct GET_Response, present),
	sizeof(((struct GET_Response *)0)->present),
	asn_MAP_GET_Response_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GET_Response = {
	"GET-Response",
	"GET-Response",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_GET_Response_constr_1,
	asn_MBR_GET_Response_1,
	6,	/* Elements count */
	&asn_SPC_GET_Response_specs_1	/* Additional specs */
};

