/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_GetRecord_H_
#define	_GetRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include "RSD.h"
#include "RCSD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetRecord */
typedef struct GetRecord {
	OAD_t	 objDescr;
	RSD_t	 rsd;
	RCSD_t	 rcsd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRecord_H_ */
#include <asn_internal.h>
