/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_GetRequestNormal_H_
#define	_GetRequestNormal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID.h"
#include "OAD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetRequestNormal */
typedef struct GetRequestNormal {
	PIID_t	 prioInvID;
	OAD_t	 objDescr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRequestNormal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRequestNormal;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRequestNormal_H_ */
#include <asn_internal.h>
