/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "GetResponseNext.h"

static asn_TYPE_member_t asn_MBR_GetResponseNext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetResponseNext, piidACD),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID_ACD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"piidACD"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetResponseNext, finalFrameFlag),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_Bool,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"finalFrameFlag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetResponseNext, frameSeq),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"frameSeq"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetResponseNext, reseponseData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ArrayOfGetResponseNextData,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reseponseData"
		},
};
static const ber_tlv_tag_t asn_DEF_GetResponseNext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetResponseNext_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* finalFrameFlag */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* piidACD */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* frameSeq */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* errCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* arrayOfaResultNormal */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 } /* arrayOfaResultRecord */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetResponseNext_specs_1 = {
	sizeof(struct GetResponseNext),
	offsetof(struct GetResponseNext, _asn_ctx),
	asn_MAP_GetResponseNext_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetResponseNext = {
	"GetResponseNext",
	"GetResponseNext",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetResponseNext_tags_1,
	sizeof(asn_DEF_GetResponseNext_tags_1)
		/sizeof(asn_DEF_GetResponseNext_tags_1[0]), /* 1 */
	asn_DEF_GetResponseNext_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetResponseNext_tags_1)
		/sizeof(asn_DEF_GetResponseNext_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetResponseNext_1,
	4,	/* Elements count */
	&asn_SPC_GetResponseNext_specs_1	/* Additional specs */
};

