/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_GetResponseRecordList_H_
#define	_GetResponseRecordList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "ArrayOfaResultRecord.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetResponseRecordList */
typedef struct GetResponseRecordList {
	PIID_ACD_t	 piidACD;
	ArrayOfaResultRecord_t	 listOfaResultRecord;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetResponseRecordList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetResponseRecordList;

#ifdef __cplusplus
}
#endif

#endif	/* _GetResponseRecordList_H_ */
#include <asn_internal.h>
