/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Integer8s_H_
#define	_Integer8s_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer8s */
typedef long	 Integer8s_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Integer8s;
asn_struct_free_f Integer8s_free;
asn_struct_print_f Integer8s_print;
asn_constr_check_f Integer8s_constraint;
ber_type_decoder_f Integer8s_decode_ber;
der_type_encoder_f Integer8s_encode_der;
xer_type_decoder_f Integer8s_decode_xer;
xer_type_encoder_f Integer8s_encode_xer;
per_type_decoder_f Integer8s_decode_uper;
per_type_encoder_f Integer8s_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Integer8s_H_ */
#include <asn_internal.h>
