/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "LINK-Request.h"

static asn_TYPE_member_t asn_MBR_LINK_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LINK_Request, piid_acd),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID_ACD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"piid-acd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LINK_Request, requestType),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_LinkRequestType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LINK_Request, heartCycle),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"heartCycle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LINK_Request, requestTime),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Date_Time,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestTime"
		},
};
static const ber_tlv_tag_t asn_DEF_LINK_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LINK_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* piid-acd */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* heartCycle */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 }, /* requestType */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* requestTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_LINK_Request_specs_1 = {
	sizeof(struct LINK_Request),
	offsetof(struct LINK_Request, _asn_ctx),
	asn_MAP_LINK_Request_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LINK_Request = {
	"LINK-Request",
	"LINK-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LINK_Request_tags_1,
	sizeof(asn_DEF_LINK_Request_tags_1)
		/sizeof(asn_DEF_LINK_Request_tags_1[0]), /* 1 */
	asn_DEF_LINK_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_LINK_Request_tags_1)
		/sizeof(asn_DEF_LINK_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LINK_Request_1,
	4,	/* Elements count */
	&asn_SPC_LINK_Request_specs_1	/* Additional specs */
};

