/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_LinkResponseResult_H_
#define	_LinkResponseResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Bit-string.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LinkResponseResult */
typedef Bit_string_t	 LinkResponseResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LinkResponseResult;
asn_struct_free_f LinkResponseResult_free;
asn_struct_print_f LinkResponseResult_print;
asn_constr_check_f LinkResponseResult_constraint;
ber_type_decoder_f LinkResponseResult_decode_ber;
der_type_encoder_f LinkResponseResult_encode_der;
xer_type_decoder_f LinkResponseResult_decode_xer;
xer_type_encoder_f LinkResponseResult_encode_xer;
per_type_decoder_f LinkResponseResult_decode_uper;
per_type_encoder_f LinkResponseResult_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LinkResponseResult_H_ */
#include <asn_internal.h>
