/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_LinkRequestType_H_
#define	_LinkRequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LinkRequestType {
	LinkRequestType_login	= 0,
	LinkRequestType_heartBeat	= 1,
	LinkRequestType_exit	= 2
} e_LinkRequestType;

/* LinkRequestType */
typedef long	 LinkRequestType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LinkRequestType;
asn_struct_free_f LinkRequestType_free;
asn_struct_print_f LinkRequestType_print;
asn_constr_check_f LinkRequestType_constraint;
ber_type_decoder_f LinkRequestType_decode_ber;
der_type_encoder_f LinkRequestType_encode_der;
xer_type_decoder_f LinkRequestType_decode_xer;
xer_type_encoder_f LinkRequestType_encode_xer;
per_type_decoder_f LinkRequestType_decode_uper;
per_type_encoder_f LinkRequestType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LinkRequestType_H_ */
#include <asn_internal.h>
