/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_LINK_Request_H_
#define	_LINK_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "LinkRequestType.h"
#include "LongUnsigned.h"
#include "Date-Time.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LINK-Request */
typedef struct LINK_Request {
	PIID_ACD_t	 piid_acd;
	LinkRequestType_t	 requestType;
	LongUnsigned_t	 heartCycle;
	Date_Time_t	 requestTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LINK_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LINK_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _LINK_Request_H_ */
#include <asn_internal.h>
