/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_LINK_APDU_H_
#define	_LINK_APDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LINK-Request.h"
#include "LINK-Response.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LINK_APDU_PR {
	LINK_APDU_PR_NOTHING,	/* No components present */
	LINK_APDU_PR_linkRequest,
	LINK_APDU_PR_linkResponse
} LINK_APDU_PR;

/* LINK-APDU */
typedef struct LINK_APDU {
	LINK_APDU_PR present;
	union LINK_APDU_u {
		LINK_Request_t	 linkRequest;
		LINK_Response_t	 linkResponse;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LINK_APDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LINK_APDU;

#ifdef __cplusplus
}
#endif

#endif	/* _LINK_APDU_H_ */
#include <asn_internal.h>
