/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_LongUnsigned_H_
#define	_LongUnsigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LongUnsigned */
typedef long	 LongUnsigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongUnsigned;
asn_struct_free_f LongUnsigned_free;
asn_struct_print_f LongUnsigned_print;
asn_constr_check_f LongUnsigned_constraint;
ber_type_decoder_f LongUnsigned_decode_ber;
der_type_encoder_f LongUnsigned_encode_der;
xer_type_decoder_f LongUnsigned_decode_xer;
xer_type_encoder_f LongUnsigned_encode_xer;
per_type_decoder_f LongUnsigned_decode_uper;
per_type_encoder_f LongUnsigned_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LongUnsigned_H_ */
#include <asn_internal.h>
