/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Long64_H_
#define	_Long64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Long64 */
typedef INTEGER_t	 Long64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Long64;
asn_struct_free_f Long64_free;
asn_struct_print_f Long64_print;
asn_constr_check_f Long64_constraint;
ber_type_decoder_f Long64_decode_ber;
der_type_encoder_f Long64_encode_der;
xer_type_decoder_f Long64_decode_xer;
xer_type_encoder_f Long64_encode_xer;
per_type_decoder_f Long64_decode_uper;
per_type_encoder_f Long64_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Long64_H_ */
#include <asn_internal.h>
