/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_MS_H_
#define	_MS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Unsigned.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "TSA.h"
#include "LongUnsigned.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MS_PR {
	MS_PR_NOTHING,	/* No components present */
	MS_PR_noMeter,
	MS_PR_allAddr,
	MS_PR_aGrpUserType,
	MS_PR_aGrpUserAddr,
	MS_PR_aGrpCfgSeq,
	MS_PR_aGrpUserTypeInterv,
	MS_PR_aGrpUserAddrInterv,
	MS_PR_aGrpUserCfgSeqInterv
} MS_PR;

/* Forward declarations */
struct Region;

/* MS */
typedef struct MS {
	MS_PR present;
	union MS_u {
		NULL_t	 noMeter;
		NULL_t	 allAddr;
		struct aGrpUserType {
			A_SEQUENCE_OF(Unsigned_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpUserType;
		struct aGrpUserAddr {
			A_SEQUENCE_OF(TSA_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpUserAddr;
		struct aGrpCfgSeq {
			A_SEQUENCE_OF(LongUnsigned_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpCfgSeq;
		struct aGrpUserTypeInterv {
			A_SEQUENCE_OF(struct Region) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpUserTypeInterv;
		struct aGrpUserAddrInterv {
			A_SEQUENCE_OF(struct Region) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpUserAddrInterv;
		struct aGrpUserCfgSeqInterv {
			A_SEQUENCE_OF(struct Region) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aGrpUserCfgSeqInterv;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MS;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Region.h"

#endif	/* _MS_H_ */
#include <asn_internal.h>
