/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_NullSecurity_H_
#define	_NullSecurity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NullSecurity */
typedef NULL_t	 NullSecurity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NullSecurity;
asn_struct_free_f NullSecurity_free;
asn_struct_print_f NullSecurity_print;
asn_constr_check_f NullSecurity_constraint;
ber_type_decoder_f NullSecurity_decode_ber;
der_type_encoder_f NullSecurity_encode_der;
xer_type_decoder_f NullSecurity_decode_xer;
xer_type_encoder_f NullSecurity_encode_xer;
per_type_decoder_f NullSecurity_decode_uper;
per_type_encoder_f NullSecurity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NullSecurity_H_ */
#include <asn_internal.h>
