/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OAD_DAR_A_ResultNormal_H_
#define	_OAD_DAR_A_ResultNormal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include "DAR.h"
#include "A-ResultNormal.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OAD-DAR-A-ResultNormal */
typedef struct OAD_DAR_A_ResultNormal {
	OAD_t	 oad;
	DAR_t	 dar;
	A_ResultNormal_t	 a_ResultNormal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OAD_DAR_A_ResultNormal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OAD_DAR_A_ResultNormal;

#ifdef __cplusplus
}
#endif

#endif	/* _OAD_DAR_A_ResultNormal_H_ */
#include <asn_internal.h>
