/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "OAD.h"

static int
memb_attrElemIdx_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_attrElemIdx_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  1,  255 }	/* (1..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_OAD_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OAD, objId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_OI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"objId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OAD, attrIdChara),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"attrIdChara"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OAD, attrElemIdx),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_attrElemIdx_constraint_1,
		&asn_PER_memb_attrElemIdx_constr_4,
		0,
		"attrElemIdx"
		},
};
static const ber_tlv_tag_t asn_DEF_OAD_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OAD_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* objId */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* attrIdChara */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* attrElemIdx */
};
static asn_SEQUENCE_specifics_t asn_SPC_OAD_specs_1 = {
	sizeof(struct OAD),
	offsetof(struct OAD, _asn_ctx),
	asn_MAP_OAD_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_OAD = {
	"OAD",
	"OAD",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_OAD_tags_1,
	sizeof(asn_DEF_OAD_tags_1)
		/sizeof(asn_DEF_OAD_tags_1[0]), /* 1 */
	asn_DEF_OAD_tags_1,	/* Same as above */
	sizeof(asn_DEF_OAD_tags_1)
		/sizeof(asn_DEF_OAD_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_OAD_1,
	3,	/* Elements count */
	&asn_SPC_OAD_specs_1	/* Additional specs */
};

