/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OadDar_H_
#define	_OadDar_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OAD.h"
#include "DAR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OadDar */
typedef struct OadDar {
	OAD_t	 objDescr;
	DAR_t	 res;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OadDar_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OadDar;

#ifdef __cplusplus
}
#endif

#endif	/* _OadDar_H_ */
#include <asn_internal.h>
