/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OadList_H_
#define	_OadList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OAD;

/* OadList */
typedef struct OadList {
	A_SEQUENCE_OF(struct OAD) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OadList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OadList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OAD.h"

#endif	/* _OadList_H_ */
#include <asn_internal.h>
