/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Octet_string_H_
#define	_Octet_string_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Octet-string */
typedef OCTET_STRING_t	 Octet_string_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Octet_string;
asn_struct_free_f Octet_string_free;
asn_struct_print_f Octet_string_print;
asn_constr_check_f Octet_string_constraint;
ber_type_decoder_f Octet_string_decode_ber;
der_type_encoder_f Octet_string_encode_der;
xer_type_decoder_f Octet_string_decode_xer;
xer_type_encoder_f Octet_string_encode_xer;
per_type_decoder_f Octet_string_decode_uper;
per_type_encoder_f Octet_string_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Octet_string_H_ */
#include <asn_internal.h>
