/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OI_H_
#define	_OI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongUnsigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OI */
typedef LongUnsigned_t	 OI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OI;
asn_struct_free_f OI_free;
asn_struct_print_f OI_print;
asn_constr_check_f OI_constraint;
ber_type_decoder_f OI_decode_ber;
der_type_encoder_f OI_encode_der;
xer_type_decoder_f OI_decode_xer;
xer_type_encoder_f OI_encode_xer;
per_type_decoder_f OI_decode_uper;
per_type_encoder_f OI_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OI_H_ */
#include <asn_internal.h>
