/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OMD_DAR_DATAOPTION_A_ResultNormal_H_
#define	_OMD_DAR_DATAOPTION_A_ResultNormal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OMD.h"
#include "DAR.h"
#include "A-ResultNormal.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data;

/* OMD-DAR-DATAOPTION-A-ResultNormal */
typedef struct OMD_DAR_DATAOPTION_A_ResultNormal {
	OMD_t	 objMethDescr;
	DAR_t	 dar;
	struct Data	*data	/* OPTIONAL */;
	A_ResultNormal_t	 a_ResultNormal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OMD_DAR_DATAOPTION_A_ResultNormal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OMD_DAR_DATAOPTION_A_ResultNormal;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _OMD_DAR_DATAOPTION_A_ResultNormal_H_ */
#include <asn_internal.h>
