/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_OmdData_H_
#define	_OmdData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OMD.h"
#include "Data.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OmdData */
typedef struct OmdData {
	OMD_t	 objMethDescr;
	Data_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OmdData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OmdData;

#ifdef __cplusplus
}
#endif

#endif	/* _OmdData_H_ */
#include <asn_internal.h>
