/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_PasswordSecurity_H_
#define	_PasswordSecurity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Visible-string.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PasswordSecurity */
typedef Visible_string_t	 PasswordSecurity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PasswordSecurity;
asn_struct_free_f PasswordSecurity_free;
asn_struct_print_f PasswordSecurity_print;
asn_constr_check_f PasswordSecurity_constraint;
ber_type_decoder_f PasswordSecurity_decode_ber;
der_type_encoder_f PasswordSecurity_encode_der;
xer_type_decoder_f PasswordSecurity_decode_xer;
xer_type_encoder_f PasswordSecurity_encode_xer;
per_type_decoder_f PasswordSecurity_decode_uper;
per_type_encoder_f PasswordSecurity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PasswordSecurity_H_ */
#include <asn_internal.h>
