/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Array;
extern struct asn_TYPE_descriptor_s asn_DEF_Structure;
extern struct asn_TYPE_descriptor_s asn_DEF_Bool;
extern struct asn_TYPE_descriptor_s asn_DEF_Bit_string;
extern struct asn_TYPE_descriptor_s asn_DEF_DoubleLong;
extern struct asn_TYPE_descriptor_s asn_DEF_DoubleLongUnsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_Octet_string;
extern struct asn_TYPE_descriptor_s asn_DEF_Visible_string;
extern struct asn_TYPE_descriptor_s asn_DEF_UTF8_string;
extern struct asn_TYPE_descriptor_s asn_DEF_Integer8s;
extern struct asn_TYPE_descriptor_s asn_DEF_Long;
extern struct asn_TYPE_descriptor_s asn_DEF_Unsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_LongUnsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_Long64;
extern struct asn_TYPE_descriptor_s asn_DEF_Long64Unsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_Enum;
extern struct asn_TYPE_descriptor_s asn_DEF_Float32;
extern struct asn_TYPE_descriptor_s asn_DEF_Float64;
extern struct asn_TYPE_descriptor_s asn_DEF_Date_Time;
extern struct asn_TYPE_descriptor_s asn_DEF_Date;
extern struct asn_TYPE_descriptor_s asn_DEF_Time;
extern struct asn_TYPE_descriptor_s asn_DEF_Date_Time_S;
extern struct asn_TYPE_descriptor_s asn_DEF_OI;
extern struct asn_TYPE_descriptor_s asn_DEF_OAD;
extern struct asn_TYPE_descriptor_s asn_DEF_OadList;
extern struct asn_TYPE_descriptor_s asn_DEF_ROAD;
extern struct asn_TYPE_descriptor_s asn_DEF_OMD;
extern struct asn_TYPE_descriptor_s asn_DEF_TI;
extern struct asn_TYPE_descriptor_s asn_DEF_TSA;
extern struct asn_TYPE_descriptor_s asn_DEF_MAC;
extern struct asn_TYPE_descriptor_s asn_DEF_RN;
extern struct asn_TYPE_descriptor_s asn_DEF_Region;
extern struct asn_TYPE_descriptor_s asn_DEF_ScalerUnit;
extern struct asn_TYPE_descriptor_s asn_DEF_RSD;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector1;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector2;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector3;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector4;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector5;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector6;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector7;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector8;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector9;
extern struct asn_TYPE_descriptor_s asn_DEF_Selector10;
extern struct asn_TYPE_descriptor_s asn_DEF_RCSD;
extern struct asn_TYPE_descriptor_s asn_DEF_CSD;
extern struct asn_TYPE_descriptor_s asn_DEF_MS;
extern struct asn_TYPE_descriptor_s asn_DEF_DAR;
extern struct asn_TYPE_descriptor_s asn_DEF_PhysicalUnit;
extern struct asn_TYPE_descriptor_s asn_DEF_SID;
extern struct asn_TYPE_descriptor_s asn_DEF_SID_MAC;
extern struct asn_TYPE_descriptor_s asn_DEF_BaudRate;
extern struct asn_TYPE_descriptor_s asn_DEF_Parity;
extern struct asn_TYPE_descriptor_s asn_DEF_DataBits;
extern struct asn_TYPE_descriptor_s asn_DEF_StopBits;
extern struct asn_TYPE_descriptor_s asn_DEF_FlowCtl;
extern struct asn_TYPE_descriptor_s asn_DEF_COMDCB;
extern struct asn_TYPE_descriptor_s asn_DEF_PIID;
extern struct asn_TYPE_descriptor_s asn_DEF_PIID_ACD;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectMechanismInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_NullSecurity;
extern struct asn_TYPE_descriptor_s asn_DEF_PasswordSecurity;
extern struct asn_TYPE_descriptor_s asn_DEF_SymmetrySecurity;
extern struct asn_TYPE_descriptor_s asn_DEF_SignatureSecurity;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectResult;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectResponseInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityData;
extern struct asn_TYPE_descriptor_s asn_DEF_Data;
extern struct asn_TYPE_descriptor_s asn_DEF_LINK_APDU;
extern struct asn_TYPE_descriptor_s asn_DEF_Client_APDU;
extern struct asn_TYPE_descriptor_s asn_DEF_Server_APDU;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfaResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfaResultRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_FollowReport;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeTag;
extern struct asn_TYPE_descriptor_s asn_DEF_SECURITY_APDU;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkRequestType;
extern struct asn_TYPE_descriptor_s asn_DEF_LINK_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_LinkResponseResult;
extern struct asn_TYPE_descriptor_s asn_DEF_LINK_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_CONNECT_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_CONNECT_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_FactoryVersion;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtocolConformance;
extern struct asn_TYPE_descriptor_s asn_DEF_FunctionConformance;
extern struct asn_TYPE_descriptor_s asn_DEF_RELEASE_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_ReleaseResponseResult;
extern struct asn_TYPE_descriptor_s asn_DEF_RELEASE_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_RELEASE_Notification;
extern struct asn_TYPE_descriptor_s asn_DEF_GET_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfGetRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestRecordList;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestNext;
extern struct asn_TYPE_descriptor_s asn_DEF_GetRequestMD5;
extern struct asn_TYPE_descriptor_s asn_DEF_GET_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_A_ResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_Get_Result;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_A_RecordRow;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfaRecordRow;
extern struct asn_TYPE_descriptor_s asn_DEF_ResponseData;
extern struct asn_TYPE_descriptor_s asn_DEF_A_ResultRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseRecordList;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfGetResponseNextData;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseNext;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseMD5result;
extern struct asn_TYPE_descriptor_s asn_DEF_GetResponseMD5;
extern struct asn_TYPE_descriptor_s asn_DEF_SET_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_SetRequestNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_OadData;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOadData;
extern struct asn_TYPE_descriptor_s asn_DEF_SetRequestNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_SetThenGet;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfSetThenGet;
extern struct asn_TYPE_descriptor_s asn_DEF_SetThenGetRequestNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_SET_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_SetResponseNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_OadDar;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOadDar;
extern struct asn_TYPE_descriptor_s asn_DEF_SetResponseNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_SetThenReponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfSetThenReponse;
extern struct asn_TYPE_descriptor_s asn_DEF_SetThenGetResponseNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_ACTION_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionRequestNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_OmdData;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOmdData;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionRequestNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_OmdDataOadUnsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOmdDataOadUnsigned;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionThenGetRequestNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_ACTION_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_OmdDarDataOPTIONAL;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionResponseNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOmdDarDataOPTIONAL;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionResponseNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfActionThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionThenGetResponseNormalList;
extern struct asn_TYPE_descriptor_s asn_DEF_REPORT_Notification;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportNotificationList;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportNotificationRecordList;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOctet;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportNotificationTransData;
extern struct asn_TYPE_descriptor_s asn_DEF_REPORT_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportResponseRecordList;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportResponseTransData;
extern struct asn_TYPE_descriptor_s asn_DEF_PROXY_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyRequestTSAOAD;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxyRequestTSAOAD;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyGetRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyGetRequestRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetList;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxySetList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_SetThenGetRequestOneTsa;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfSetThenGetRequestOneTsa;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetThenGetRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxyActionRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionThenGetRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxyActionThenGetRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionThenGetRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyTransCommandRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_PROXY_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyGetResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyGetResponseRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfArrayOfOadDar;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxySetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_OAD_DAR_A_ResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOAD_DAR_A_ResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxySetThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxySetThenGetResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxyActionResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_OMD_DAR_DATAOPTION_A_ResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ArrayOfProxyActionThenGetResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyActionThenGetResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_ProxyTransCommandResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_TransResult;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityRequestApdu;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityRequestChkInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SECURITY_Request;
extern struct asn_TYPE_descriptor_s asn_DEF_RN_MAC;
extern struct asn_TYPE_descriptor_s asn_DEF_DataChkInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityResponseApdu;
extern struct asn_TYPE_descriptor_s asn_DEF_SECURITY_Response;
extern struct asn_TYPE_descriptor_s asn_DEF_ErrorResponseType;
extern struct asn_TYPE_descriptor_s asn_DEF_ERROR_Response;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module DLT69845 in dlt698.45.asn1 */
	&asn_DEF_Array,	
	&asn_DEF_Structure,	
	&asn_DEF_Bool,	
	&asn_DEF_Bit_string,	
	&asn_DEF_DoubleLong,	
	&asn_DEF_DoubleLongUnsigned,	
	&asn_DEF_Octet_string,	
	&asn_DEF_Visible_string,	
	&asn_DEF_UTF8_string,	
	&asn_DEF_Integer8s,	
	&asn_DEF_Long,	
	&asn_DEF_Unsigned,	
	&asn_DEF_LongUnsigned,	
	&asn_DEF_Long64,	
	&asn_DEF_Long64Unsigned,	
	&asn_DEF_Enum,	
	&asn_DEF_Float32,	
	&asn_DEF_Float64,	
	&asn_DEF_Date_Time,	
	&asn_DEF_Date,	
	&asn_DEF_Time,	
	&asn_DEF_Date_Time_S,	
	&asn_DEF_OI,	
	&asn_DEF_OAD,	
	&asn_DEF_OadList,	
	&asn_DEF_ROAD,	
	&asn_DEF_OMD,	
	&asn_DEF_TI,	
	&asn_DEF_TSA,	
	&asn_DEF_MAC,	
	&asn_DEF_RN,	
	&asn_DEF_Region,	
	&asn_DEF_ScalerUnit,	
	&asn_DEF_RSD,	
	&asn_DEF_Selector1,	
	&asn_DEF_Selector2,	
	&asn_DEF_Selector3,	
	&asn_DEF_Selector4,	
	&asn_DEF_Selector5,	
	&asn_DEF_Selector6,	
	&asn_DEF_Selector7,	
	&asn_DEF_Selector8,	
	&asn_DEF_Selector9,	
	&asn_DEF_Selector10,	
	&asn_DEF_RCSD,	
	&asn_DEF_CSD,	
	&asn_DEF_MS,	
	&asn_DEF_DAR,	
	&asn_DEF_PhysicalUnit,	
	&asn_DEF_SID,	
	&asn_DEF_SID_MAC,	
	&asn_DEF_BaudRate,	
	&asn_DEF_Parity,	
	&asn_DEF_DataBits,	
	&asn_DEF_StopBits,	
	&asn_DEF_FlowCtl,	
	&asn_DEF_COMDCB,	
	&asn_DEF_PIID,	
	&asn_DEF_PIID_ACD,	
	&asn_DEF_ConnectMechanismInfo,	
	&asn_DEF_NullSecurity,	
	&asn_DEF_PasswordSecurity,	
	&asn_DEF_SymmetrySecurity,	
	&asn_DEF_SignatureSecurity,	
	&asn_DEF_ConnectResult,	
	&asn_DEF_ConnectResponseInfo,	
	&asn_DEF_SecurityData,	
	&asn_DEF_Data,	
	&asn_DEF_LINK_APDU,	
	&asn_DEF_Client_APDU,	
	&asn_DEF_Server_APDU,	
	&asn_DEF_ArrayOfaResultNormal,	
	&asn_DEF_ArrayOfaResultRecord,	
	&asn_DEF_FollowReport,	
	&asn_DEF_TimeTag,	
	&asn_DEF_SECURITY_APDU,	
	&asn_DEF_LinkRequestType,	
	&asn_DEF_LINK_Request,	
	&asn_DEF_LinkResponseResult,	
	&asn_DEF_LINK_Response,	
	&asn_DEF_CONNECT_Request,	
	&asn_DEF_CONNECT_Response,	
	&asn_DEF_FactoryVersion,	
	&asn_DEF_ProtocolConformance,	
	&asn_DEF_FunctionConformance,	
	&asn_DEF_RELEASE_Request,	
	&asn_DEF_ReleaseResponseResult,	
	&asn_DEF_RELEASE_Response,	
	&asn_DEF_RELEASE_Notification,	
	&asn_DEF_GET_Request,	
	&asn_DEF_GetRequestNormal,	
	&asn_DEF_GetRequestNormalList,	
	&asn_DEF_GetRequestRecord,	
	&asn_DEF_GetRecord,	
	&asn_DEF_ArrayOfGetRecord,	
	&asn_DEF_GetRequestRecordList,	
	&asn_DEF_GetRequestNext,	
	&asn_DEF_GetRequestMD5,	
	&asn_DEF_GET_Response,	
	&asn_DEF_GetResponseNormal,	
	&asn_DEF_A_ResultNormal,	
	&asn_DEF_Get_Result,	
	&asn_DEF_GetResponseNormalList,	
	&asn_DEF_GetResponseRecord,	
	&asn_DEF_A_RecordRow,	
	&asn_DEF_ArrayOfaRecordRow,	
	&asn_DEF_ResponseData,	
	&asn_DEF_A_ResultRecord,	
	&asn_DEF_GetResponseRecordList,	
	&asn_DEF_ArrayOfGetResponseNextData,	
	&asn_DEF_GetResponseNext,	
	&asn_DEF_GetResponseMD5result,	
	&asn_DEF_GetResponseMD5,	
	&asn_DEF_SET_Request,	
	&asn_DEF_SetRequestNormal,	
	&asn_DEF_OadData,	
	&asn_DEF_ArrayOfOadData,	
	&asn_DEF_SetRequestNormalList,	
	&asn_DEF_SetThenGet,	
	&asn_DEF_ArrayOfSetThenGet,	
	&asn_DEF_SetThenGetRequestNormalList,	
	&asn_DEF_SET_Response,	
	&asn_DEF_SetResponseNormal,	
	&asn_DEF_OadDar,	
	&asn_DEF_ArrayOfOadDar,	
	&asn_DEF_SetResponseNormalList,	
	&asn_DEF_SetThenReponse,	
	&asn_DEF_ArrayOfSetThenReponse,	
	&asn_DEF_SetThenGetResponseNormalList,	
	&asn_DEF_ACTION_Request,	
	&asn_DEF_ActionRequestNormal,	
	&asn_DEF_OmdData,	
	&asn_DEF_ArrayOfOmdData,	
	&asn_DEF_ActionRequestNormalList,	
	&asn_DEF_OmdDataOadUnsigned,	
	&asn_DEF_ArrayOfOmdDataOadUnsigned,	
	&asn_DEF_ActionThenGetRequestNormalList,	
	&asn_DEF_ACTION_Response,	
	&asn_DEF_OmdDarDataOPTIONAL,	
	&asn_DEF_ActionResponseNormal,	
	&asn_DEF_ArrayOfOmdDarDataOPTIONAL,	
	&asn_DEF_ActionResponseNormalList,	
	&asn_DEF_ActionThenGetResponse,	
	&asn_DEF_ArrayOfActionThenGetResponse,	
	&asn_DEF_ActionThenGetResponseNormalList,	
	&asn_DEF_REPORT_Notification,	
	&asn_DEF_ReportNotificationList,	
	&asn_DEF_ReportNotificationRecordList,	
	&asn_DEF_ArrayOfOctet,	
	&asn_DEF_ReportNotificationTransData,	
	&asn_DEF_REPORT_Response,	
	&asn_DEF_ReportResponseList,	
	&asn_DEF_ReportResponseRecordList,	
	&asn_DEF_ReportResponseTransData,	
	&asn_DEF_PROXY_Request,	
	&asn_DEF_ProxyRequestTSAOAD,	
	&asn_DEF_ArrayOfProxyRequestTSAOAD,	
	&asn_DEF_ProxyGetRequestList,	
	&asn_DEF_ProxyGetRequestRecord,	
	&asn_DEF_ProxySetList,	
	&asn_DEF_ArrayOfProxySetList,	
	&asn_DEF_ProxySetRequestList,	
	&asn_DEF_SetThenGetRequestOneTsa,	
	&asn_DEF_ArrayOfSetThenGetRequestOneTsa,	
	&asn_DEF_ProxySetThenGetRequestList,	
	&asn_DEF_ProxyActionRequest,	
	&asn_DEF_ArrayOfProxyActionRequest,	
	&asn_DEF_ProxyActionRequestList,	
	&asn_DEF_ProxyActionThenGetRequest,	
	&asn_DEF_ArrayOfProxyActionThenGetRequest,	
	&asn_DEF_ProxyActionThenGetRequestList,	
	&asn_DEF_ProxyTransCommandRequest,	
	&asn_DEF_PROXY_Response,	
	&asn_DEF_ProxyGetResponseList,	
	&asn_DEF_ProxyGetResponseRecord,	
	&asn_DEF_ArrayOfArrayOfOadDar,	
	&asn_DEF_ProxySetResponse,	
	&asn_DEF_ArrayOfProxySetResponse,	
	&asn_DEF_ProxySetResponseList,	
	&asn_DEF_OAD_DAR_A_ResultNormal,	
	&asn_DEF_ArrayOfOAD_DAR_A_ResultNormal,	
	&asn_DEF_ProxySetThenGetResponse,	
	&asn_DEF_ArrayOfProxySetThenGetResponse,	
	&asn_DEF_ProxySetThenGetResponseList,	
	&asn_DEF_ProxyActionResponse,	
	&asn_DEF_ArrayOfProxyActionResponse,	
	&asn_DEF_ProxyActionResponseList,	
	&asn_DEF_OMD_DAR_DATAOPTION_A_ResultNormal,	
	&asn_DEF_ArrayOfOMD_DAR_DATAOPTION_A_ResultNormal,	
	&asn_DEF_ProxyActionThenGetResponse,	
	&asn_DEF_ArrayOfProxyActionThenGetResponse,	
	&asn_DEF_ProxyActionThenGetResponseList,	
	&asn_DEF_ProxyTransCommandResponse,	
	&asn_DEF_TransResult,	
	&asn_DEF_SecurityRequestApdu,	
	&asn_DEF_SecurityRequestChkInfo,	
	&asn_DEF_SECURITY_Request,	
	&asn_DEF_RN_MAC,	
	&asn_DEF_DataChkInfo,	
	&asn_DEF_SecurityResponseApdu,	
	&asn_DEF_SECURITY_Response,	
	&asn_DEF_ErrorResponseType,	
	&asn_DEF_ERROR_Response,	
	0
};

