/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_PhysicalUnit_H_
#define	_PhysicalUnit_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PhysicalUnit {
	PhysicalUnit_a	= 1,
	PhysicalUnit_mo	= 2,
	PhysicalUnit_wk	= 3,
	PhysicalUnit_d	= 4,
	PhysicalUnit_h	= 5,
	PhysicalUnit_min	= 6,
	PhysicalUnit_s	= 7,
	PhysicalUnit_rad	= 8,
	PhysicalUnit_tK	= 9,
	PhysicalUnit_currency	= 10,
	PhysicalUnit_m	= 11,
	PhysicalUnit_mPerSec	= 12,
	PhysicalUnit_squareMeter	= 13,
	PhysicalUnit_sqMeter	= 14,
	PhysicalUnit_sqMeterPerHour	= 15
} e_PhysicalUnit;

/* PhysicalUnit */
typedef long	 PhysicalUnit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalUnit;
asn_struct_free_f PhysicalUnit_free;
asn_struct_print_f PhysicalUnit_print;
asn_constr_check_f PhysicalUnit_constraint;
ber_type_decoder_f PhysicalUnit_decode_ber;
der_type_encoder_f PhysicalUnit_encode_der;
xer_type_decoder_f PhysicalUnit_decode_xer;
xer_type_encoder_f PhysicalUnit_encode_xer;
per_type_decoder_f PhysicalUnit_decode_uper;
per_type_encoder_f PhysicalUnit_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalUnit_H_ */
#include <asn_internal.h>
