/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "ProtocolConformance.h"

int
ProtocolConformance_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const Bit_string_t *st = (const Bit_string_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using Bit_string,
 * so here we adjust the DEF accordingly.
 */
static void
ProtocolConformance_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_Bit_string.free_struct;
	td->print_struct   = asn_DEF_Bit_string.print_struct;
	td->check_constraints = asn_DEF_Bit_string.check_constraints;
	td->ber_decoder    = asn_DEF_Bit_string.ber_decoder;
	td->der_encoder    = asn_DEF_Bit_string.der_encoder;
	td->xer_decoder    = asn_DEF_Bit_string.xer_decoder;
	td->xer_encoder    = asn_DEF_Bit_string.xer_encoder;
	td->uper_decoder   = asn_DEF_Bit_string.uper_decoder;
	td->uper_encoder   = asn_DEF_Bit_string.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_Bit_string.per_constraints;
	td->elements       = asn_DEF_Bit_string.elements;
	td->elements_count = asn_DEF_Bit_string.elements_count;
	td->specifics      = asn_DEF_Bit_string.specifics;
}

void
ProtocolConformance_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
ProtocolConformance_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
ProtocolConformance_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
ProtocolConformance_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
ProtocolConformance_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
ProtocolConformance_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
ProtocolConformance_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
ProtocolConformance_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	ProtocolConformance_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_ProtocolConformance_constr_1 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  64,  64 }	/* (SIZE(64..64)) */,
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_ProtocolConformance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (3 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolConformance = {
	"ProtocolConformance",
	"ProtocolConformance",
	ProtocolConformance_free,
	ProtocolConformance_print,
	ProtocolConformance_constraint,
	ProtocolConformance_decode_ber,
	ProtocolConformance_encode_der,
	ProtocolConformance_decode_xer,
	ProtocolConformance_encode_xer,
	ProtocolConformance_decode_uper,
	ProtocolConformance_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProtocolConformance_tags_1,
	sizeof(asn_DEF_ProtocolConformance_tags_1)
		/sizeof(asn_DEF_ProtocolConformance_tags_1[0]), /* 1 */
	asn_DEF_ProtocolConformance_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolConformance_tags_1)
		/sizeof(asn_DEF_ProtocolConformance_tags_1[0]), /* 1 */
	&asn_PER_type_ProtocolConformance_constr_1,
	0, 0,	/* No members */
	0	/* No specifics */
};

