/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProtocolConformance_H_
#define	_ProtocolConformance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Bit-string.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolConformance */
typedef Bit_string_t	 ProtocolConformance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolConformance;
asn_struct_free_f ProtocolConformance_free;
asn_struct_print_f ProtocolConformance_print;
asn_constr_check_f ProtocolConformance_constraint;
ber_type_decoder_f ProtocolConformance_decode_ber;
der_type_encoder_f ProtocolConformance_encode_der;
xer_type_decoder_f ProtocolConformance_decode_xer;
xer_type_encoder_f ProtocolConformance_encode_xer;
per_type_decoder_f ProtocolConformance_decode_uper;
per_type_encoder_f ProtocolConformance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolConformance_H_ */
#include <asn_internal.h>
