/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxySetList_H_
#define	_ProxySetList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TSA.h"
#include "LongUnsigned.h"
#include "ArrayOfOadData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxySetList */
typedef struct ProxySetList {
	TSA_t	 tsa;
	LongUnsigned_t	 delay;
	ArrayOfOadData_t	 arrayOfOadData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxySetList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxySetList;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxySetList_H_ */
#include <asn_internal.h>
