/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxySetResponse_H_
#define	_ProxySetResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TSA.h"
#include "ArrayOfArrayOfOadDar.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxySetResponse */
typedef struct ProxySetResponse {
	TSA_t	 tsa;
	ArrayOfArrayOfOadDar_t	 listOfRes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxySetResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxySetResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxySetResponse_H_ */
#include <asn_internal.h>
