/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "PROXY-Response.h"

static asn_per_constraints_t asn_PER_type_PROXY_Response_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_PROXY_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxyGetResponseList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxyGetResponseList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyGetResponseList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxyGetResponseRecord),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxyGetResponseRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyGetResponseRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxySetResponseList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxySetResponseList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxySetResponseList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxySetThenGetResponseList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxySetThenGetResponseList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxySetThenGetResponseList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxyActionResponseList),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxyActionResponseList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyActionResponseList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxyActionThenGetResponseList),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxyActionThenGetResponseList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyActionThenGetResponseList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PROXY_Response, choice.proxyTransCommandResponse),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProxyTransCommandResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyTransCommandResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_PROXY_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* proxyGetResponseList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* proxyGetResponseRecord */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* proxySetResponseList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* proxySetThenGetResponseList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* proxyActionResponseList */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* proxyActionThenGetResponseList */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 } /* proxyTransCommandResponse */
};
static asn_CHOICE_specifics_t asn_SPC_PROXY_Response_specs_1 = {
	sizeof(struct PROXY_Response),
	offsetof(struct PROXY_Response, _asn_ctx),
	offsetof(struct PROXY_Response, present),
	sizeof(((struct PROXY_Response *)0)->present),
	asn_MAP_PROXY_Response_tag2el_1,
	7,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PROXY_Response = {
	"PROXY-Response",
	"PROXY-Response",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_PROXY_Response_constr_1,
	asn_MBR_PROXY_Response_1,
	7,	/* Elements count */
	&asn_SPC_PROXY_Response_specs_1	/* Additional specs */
};

