/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyTransCommandRequest_H_
#define	_ProxyTransCommandRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID.h"
#include "OAD.h"
#include "COMDCB.h"
#include "LongUnsigned.h"
#include "Octet-string.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxyTransCommandRequest */
typedef struct ProxyTransCommandRequest {
	PIID_t	 prioInvID;
	OAD_t	 oad;
	COMDCB_t	 comConfig;
	LongUnsigned_t	 delaySec;
	LongUnsigned_t	 delayMilliSec;
	Octet_string_t	 cmd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyTransCommandRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyTransCommandRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxyTransCommandRequest_H_ */
#include <asn_internal.h>
