/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyActionRequestList_H_
#define	_ProxyActionRequestList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID.h"
#include "LongUnsigned.h"
#include "ArrayOfProxyActionRequest.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxyActionRequestList */
typedef struct ProxyActionRequestList {
	PIID_t	 prioInvID;
	LongUnsigned_t	 delay;
	ArrayOfProxyActionRequest_t	 proxyActionRequestList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyActionRequestList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyActionRequestList;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxyActionRequestList_H_ */
#include <asn_internal.h>
