/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "ProxyTransCommandResponse.h"

static asn_TYPE_member_t asn_MBR_ProxyTransCommandResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandResponse, piidACD),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID_ACD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"piidACD"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandResponse, oad),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"oad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandResponse, res),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_TransResult,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"res"
		},
};
static const ber_tlv_tag_t asn_DEF_ProxyTransCommandResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProxyTransCommandResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* piidACD */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* dar */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 } /* retData */
};
static asn_SEQUENCE_specifics_t asn_SPC_ProxyTransCommandResponse_specs_1 = {
	sizeof(struct ProxyTransCommandResponse),
	offsetof(struct ProxyTransCommandResponse, _asn_ctx),
	asn_MAP_ProxyTransCommandResponse_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ProxyTransCommandResponse = {
	"ProxyTransCommandResponse",
	"ProxyTransCommandResponse",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProxyTransCommandResponse_tags_1,
	sizeof(asn_DEF_ProxyTransCommandResponse_tags_1)
		/sizeof(asn_DEF_ProxyTransCommandResponse_tags_1[0]), /* 1 */
	asn_DEF_ProxyTransCommandResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProxyTransCommandResponse_tags_1)
		/sizeof(asn_DEF_ProxyTransCommandResponse_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProxyTransCommandResponse_1,
	3,	/* Elements count */
	&asn_SPC_ProxyTransCommandResponse_specs_1	/* Additional specs */
};

