/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_PROXY_Response_H_
#define	_PROXY_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProxyGetResponseList.h"
#include "ProxyGetResponseRecord.h"
#include "ProxySetResponseList.h"
#include "ProxySetThenGetResponseList.h"
#include "ProxyActionResponseList.h"
#include "ProxyActionThenGetResponseList.h"
#include "ProxyTransCommandResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PROXY_Response_PR {
	PROXY_Response_PR_NOTHING,	/* No components present */
	PROXY_Response_PR_proxyGetResponseList,
	PROXY_Response_PR_proxyGetResponseRecord,
	PROXY_Response_PR_proxySetResponseList,
	PROXY_Response_PR_proxySetThenGetResponseList,
	PROXY_Response_PR_proxyActionResponseList,
	PROXY_Response_PR_proxyActionThenGetResponseList,
	PROXY_Response_PR_proxyTransCommandResponse
} PROXY_Response_PR;

/* PROXY-Response */
typedef struct PROXY_Response {
	PROXY_Response_PR present;
	union PROXY_Response_u {
		ProxyGetResponseList_t	 proxyGetResponseList;
		ProxyGetResponseRecord_t	 proxyGetResponseRecord;
		ProxySetResponseList_t	 proxySetResponseList;
		ProxySetThenGetResponseList_t	 proxySetThenGetResponseList;
		ProxyActionResponseList_t	 proxyActionResponseList;
		ProxyActionThenGetResponseList_t	 proxyActionThenGetResponseList;
		ProxyTransCommandResponse_t	 proxyTransCommandResponse;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PROXY_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PROXY_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _PROXY_Response_H_ */
#include <asn_internal.h>
