/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_PROXY_Request_H_
#define	_PROXY_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProxyGetRequestList.h"
#include "ProxyGetRequestRecord.h"
#include "ProxySetRequestList.h"
#include "ProxySetThenGetRequestList.h"
#include "ProxyActionRequestList.h"
#include "ProxyActionThenGetRequestList.h"
#include "ProxyTransCommandRequest.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PROXY_Request_PR {
	PROXY_Request_PR_NOTHING,	/* No components present */
	PROXY_Request_PR_proxyGetRequestList,
	PROXY_Request_PR_proxyGetRequestRecord,
	PROXY_Request_PR_proxySetRequestList,
	PROXY_Request_PR_proxySetThenGetRequestList,
	PROXY_Request_PR_proxyActionRequestList,
	PROXY_Request_PR_proxyActionThenGetRequestList,
	PROXY_Request_PR_proxyTransCommandRequest
} PROXY_Request_PR;

/* PROXY-Request */
typedef struct PROXY_Request {
	PROXY_Request_PR present;
	union PROXY_Request_u {
		ProxyGetRequestList_t	 proxyGetRequestList;
		ProxyGetRequestRecord_t	 proxyGetRequestRecord;
		ProxySetRequestList_t	 proxySetRequestList;
		ProxySetThenGetRequestList_t	 proxySetThenGetRequestList;
		ProxyActionRequestList_t	 proxyActionRequestList;
		ProxyActionThenGetRequestList_t	 proxyActionThenGetRequestList;
		ProxyTransCommandRequest_t	 proxyTransCommandRequest;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PROXY_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PROXY_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _PROXY_Request_H_ */
#include <asn_internal.h>
