/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyGetResponseRecord_H_
#define	_ProxyGetResponseRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "TSA.h"
#include "A-ResultRecord.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxyGetResponseRecord */
typedef struct ProxyGetResponseRecord {
	PIID_ACD_t	 piidACD;
	TSA_t	 tsa;
	A_ResultRecord_t	 a_ResultRecord;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyGetResponseRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyGetResponseRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxyGetResponseRecord_H_ */
#include <asn_internal.h>
