/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "ProxyTransCommandRequest.h"

static asn_TYPE_member_t asn_MBR_ProxyTransCommandRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, prioInvID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_PIID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"prioInvID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, oad),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"oad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, comConfig),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_COMDCB,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"comConfig"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, delaySec),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"delaySec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, delayMilliSec),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LongUnsigned,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"delayMilliSec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProxyTransCommandRequest, cmd),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Octet_string,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cmd"
		},
};
static const ber_tlv_tag_t asn_DEF_ProxyTransCommandRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProxyTransCommandRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* prioInvID */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* delaySec */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 0 }, /* delayMilliSec */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 5, 0, 0 }, /* cmd */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* oad */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* comConfig */
};
static asn_SEQUENCE_specifics_t asn_SPC_ProxyTransCommandRequest_specs_1 = {
	sizeof(struct ProxyTransCommandRequest),
	offsetof(struct ProxyTransCommandRequest, _asn_ctx),
	asn_MAP_ProxyTransCommandRequest_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ProxyTransCommandRequest = {
	"ProxyTransCommandRequest",
	"ProxyTransCommandRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProxyTransCommandRequest_tags_1,
	sizeof(asn_DEF_ProxyTransCommandRequest_tags_1)
		/sizeof(asn_DEF_ProxyTransCommandRequest_tags_1[0]), /* 1 */
	asn_DEF_ProxyTransCommandRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProxyTransCommandRequest_tags_1)
		/sizeof(asn_DEF_ProxyTransCommandRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProxyTransCommandRequest_1,
	6,	/* Elements count */
	&asn_SPC_ProxyTransCommandRequest_specs_1	/* Additional specs */
};

