/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyActionResponseList_H_
#define	_ProxyActionResponseList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "ArrayOfProxyActionResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxyActionResponseList */
typedef struct ProxyActionResponseList {
	PIID_ACD_t	 piidACD;
	ArrayOfProxyActionResponse_t	 proxyActionResponseList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyActionResponseList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyActionResponseList;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxyActionResponseList_H_ */
#include <asn_internal.h>
