/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyGetResponseList_H_
#define	_ProxyGetResponseList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "TSA.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ArrayOfaResultNormal;

/* ProxyGetResponseList */
typedef struct ProxyGetResponseList {
	PIID_ACD_t	 piidACD;
	TSA_t	 tsa;
	struct proxyGetResponseList {
		A_SEQUENCE_OF(struct ArrayOfaResultNormal) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} proxyGetResponseList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyGetResponseList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyGetResponseList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ArrayOfaResultNormal.h"

#endif	/* _ProxyGetResponseList_H_ */
#include <asn_internal.h>
