/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ProxyActionThenGetRequest_H_
#define	_ProxyActionThenGetRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TSA.h"
#include "LongUnsigned.h"
#include "ArrayOfOmdDataOadUnsigned.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProxyActionThenGetRequest */
typedef struct ProxyActionThenGetRequest {
	TSA_t	 tsa;
	LongUnsigned_t	 delay;
	ArrayOfOmdDataOadUnsigned_t	 listOfOmdDataGet;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProxyActionThenGetRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProxyActionThenGetRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ProxyActionThenGetRequest_H_ */
#include <asn_internal.h>
