/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Region_H_
#define	_Region_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum regionUnit {
	regionUnit_closeOpen	= 0,
	regionUnit_openClose	= 1,
	regionUnit_closeClose	= 2,
	regionUnit_openOpen	= 3
} e_regionUnit;

/* Forward declarations */
struct Data;

/* Region */
typedef struct Region {
	long	 regionUnit;
	struct Data	*start;
	struct Data	*end;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Region_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_regionUnit_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Region;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _Region_H_ */
#include <asn_internal.h>
