/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ReleaseResponseResult_H_
#define	_ReleaseResponseResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReleaseResponseResult {
	ReleaseResponseResult_success	= 0
} e_ReleaseResponseResult;

/* ReleaseResponseResult */
typedef long	 ReleaseResponseResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReleaseResponseResult;
asn_struct_free_f ReleaseResponseResult_free;
asn_struct_print_f ReleaseResponseResult_print;
asn_constr_check_f ReleaseResponseResult_constraint;
ber_type_decoder_f ReleaseResponseResult_decode_ber;
der_type_encoder_f ReleaseResponseResult_encode_der;
xer_type_decoder_f ReleaseResponseResult_decode_xer;
xer_type_encoder_f ReleaseResponseResult_encode_xer;
per_type_decoder_f ReleaseResponseResult_decode_uper;
per_type_encoder_f ReleaseResponseResult_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReleaseResponseResult_H_ */
#include <asn_internal.h>
