/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_RELEASE_Notification_H_
#define	_RELEASE_Notification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID-ACD.h"
#include "Date-Time-S.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RELEASE-Notification */
typedef struct RELEASE_Notification {
	PIID_ACD_t	 piidACD;
	Date_Time_S_t	 appLinkEstablishTime;
	Date_Time_S_t	 svrCurrentTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RELEASE_Notification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RELEASE_Notification;

#ifdef __cplusplus
}
#endif

#endif	/* _RELEASE_Notification_H_ */
#include <asn_internal.h>
