/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ReportResponseRecordList_H_
#define	_ReportResponseRecordList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID.h"
#include "OadList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportResponseRecordList */
typedef struct ReportResponseRecordList {
	PIID_t	 prioInvID;
	OadList_t	 oadList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportResponseRecordList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportResponseRecordList;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportResponseRecordList_H_ */
#include <asn_internal.h>
