/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "REPORT-Notification.h"

static asn_per_constraints_t asn_PER_type_REPORT_Notification_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_REPORT_Notification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct REPORT_Notification, choice.reportNotificationList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReportNotificationList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportNotificationList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct REPORT_Notification, choice.reportNotificationRecordList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReportNotificationRecordList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportNotificationRecordList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct REPORT_Notification, choice.reportNotificationTransData),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ReportNotificationTransData,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportNotificationTransData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_REPORT_Notification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* reportNotificationList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* reportNotificationRecordList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* reportNotificationTransData */
};
static asn_CHOICE_specifics_t asn_SPC_REPORT_Notification_specs_1 = {
	sizeof(struct REPORT_Notification),
	offsetof(struct REPORT_Notification, _asn_ctx),
	offsetof(struct REPORT_Notification, present),
	sizeof(((struct REPORT_Notification *)0)->present),
	asn_MAP_REPORT_Notification_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_REPORT_Notification = {
	"REPORT-Notification",
	"REPORT-Notification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_REPORT_Notification_constr_1,
	asn_MBR_REPORT_Notification_1,
	3,	/* Elements count */
	&asn_SPC_REPORT_Notification_specs_1	/* Additional specs */
};

