/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_REPORT_Response_H_
#define	_REPORT_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReportResponseList.h"
#include "ReportResponseRecordList.h"
#include "ReportResponseTransData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum REPORT_Response_PR {
	REPORT_Response_PR_NOTHING,	/* No components present */
	REPORT_Response_PR_reportResponseList,
	REPORT_Response_PR_reportResponseRecordList,
	REPORT_Response_PR_reportResponseTransData
} REPORT_Response_PR;

/* REPORT-Response */
typedef struct REPORT_Response {
	REPORT_Response_PR present;
	union REPORT_Response_u {
		ReportResponseList_t	 reportResponseList;
		ReportResponseRecordList_t	 reportResponseRecordList;
		ReportResponseTransData_t	 reportResponseTransData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} REPORT_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_REPORT_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _REPORT_Response_H_ */
#include <asn_internal.h>
