/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_ResponseData_H_
#define	_ResponseData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DAR.h"
#include "ArrayOfaRecordRow.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResponseData_PR {
	ResponseData_PR_NOTHING,	/* No components present */
	ResponseData_PR_dar,
	ResponseData_PR_listOfa_RecordRow
} ResponseData_PR;

/* ResponseData */
typedef struct ResponseData {
	ResponseData_PR present;
	union ResponseData_u {
		DAR_t	 dar;
		ArrayOfaRecordRow_t	 listOfa_RecordRow;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseData;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseData_H_ */
#include <asn_internal.h>
