/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_RN_MAC_H_
#define	_RN_MAC_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RN.h"
#include "MAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RN-MAC */
typedef struct RN_MAC {
	RN_t	 rn;
	MAC_t	 mac;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RN_MAC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RN_MAC;

#ifdef __cplusplus
}
#endif

#endif	/* _RN_MAC_H_ */
#include <asn_internal.h>
