/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_RN_H_
#define	_RN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet-string.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RN */
typedef Octet_string_t	 RN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RN;
asn_struct_free_f RN_free;
asn_struct_print_f RN_print;
asn_constr_check_f RN_constraint;
ber_type_decoder_f RN_decode_ber;
der_type_encoder_f RN_encode_der;
xer_type_decoder_f RN_decode_xer;
xer_type_encoder_f RN_encode_xer;
per_type_decoder_f RN_decode_uper;
per_type_encoder_f RN_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RN_H_ */
#include <asn_internal.h>
