/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SECURITY_APDU_H_
#define	_SECURITY_APDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SECURITY-Request.h"
#include "SECURITY-Response.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SECURITY_APDU_PR {
	SECURITY_APDU_PR_NOTHING,	/* No components present */
	SECURITY_APDU_PR_security_Request,
	SECURITY_APDU_PR_security_Response
} SECURITY_APDU_PR;

/* SECURITY-APDU */
typedef struct SECURITY_APDU {
	SECURITY_APDU_PR present;
	union SECURITY_APDU_u {
		SECURITY_Request_t	 security_Request;
		SECURITY_Response_t	 security_Response;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SECURITY_APDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SECURITY_APDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SECURITY_APDU_H_ */
#include <asn_internal.h>
