/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SecurityData_H_
#define	_SecurityData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RN.h"
#include "Octet-string.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityData */
typedef struct SecurityData {
	RN_t	 svrRN;
	Octet_string_t	 svrSigInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityData;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityData_H_ */
#include <asn_internal.h>
