/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SecurityResponseApdu_H_
#define	_SecurityResponseApdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet-string.h"
#include "DAR.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityResponseApdu_PR {
	SecurityResponseApdu_PR_NOTHING,	/* No components present */
	SecurityResponseApdu_PR_plaintextApdu,
	SecurityResponseApdu_PR_cipherApdu,
	SecurityResponseApdu_PR_dar
} SecurityResponseApdu_PR;

/* SecurityResponseApdu */
typedef struct SecurityResponseApdu {
	SecurityResponseApdu_PR present;
	union SecurityResponseApdu_u {
		Octet_string_t	 plaintextApdu;
		Octet_string_t	 cipherApdu;
		DAR_t	 dar;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityResponseApdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityResponseApdu;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityResponseApdu_H_ */
#include <asn_internal.h>
