/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "SECURITY-Response.h"

static asn_TYPE_member_t asn_MBR_SECURITY_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SECURITY_Response, apdu),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SecurityResponseApdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"apdu"
		},
	{ ATF_POINTER, 1, offsetof(struct SECURITY_Response, dataChkInfo),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_DataChkInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dataChkInfo"
		},
};
static const int asn_MAP_SECURITY_Response_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_SECURITY_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SECURITY_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* plaintextApdu */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* mac */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* cipherApdu */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* dar */
};
static asn_SEQUENCE_specifics_t asn_SPC_SECURITY_Response_specs_1 = {
	sizeof(struct SECURITY_Response),
	offsetof(struct SECURITY_Response, _asn_ctx),
	asn_MAP_SECURITY_Response_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SECURITY_Response_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SECURITY_Response = {
	"SECURITY-Response",
	"SECURITY-Response",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SECURITY_Response_tags_1,
	sizeof(asn_DEF_SECURITY_Response_tags_1)
		/sizeof(asn_DEF_SECURITY_Response_tags_1[0]), /* 1 */
	asn_DEF_SECURITY_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_SECURITY_Response_tags_1)
		/sizeof(asn_DEF_SECURITY_Response_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SECURITY_Response_1,
	2,	/* Elements count */
	&asn_SPC_SECURITY_Response_specs_1	/* Additional specs */
};

