/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "Selector2.h"

static asn_TYPE_member_t asn_MBR_Selector2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Selector2, objDescr),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OAD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"objDescr"
		},
	{ ATF_POINTER, 0, offsetof(struct Selector2, startValue),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"startValue"
		},
	{ ATF_POINTER, 0, offsetof(struct Selector2, endValue),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"endValue"
		},
	{ ATF_POINTER, 0, offsetof(struct Selector2, interv),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interv"
		},
};
static const ber_tlv_tag_t asn_DEF_Selector2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Selector2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* objDescr */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 2 }, /* null */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, -1, 1 }, /* null */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, -2, 0 }, /* null */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 2 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, -1, 1 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, -2, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 2 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, -1, 1 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, -2, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 2 }, /* bool */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, -1, 1 }, /* bool */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, -2, 0 }, /* bool */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 2 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, -1, 1 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, -2, 0 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 2 }, /* doubleLong */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, -1, 1 }, /* doubleLong */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 3, -2, 0 }, /* doubleLong */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 2 }, /* doubleLongunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 2, -1, 1 }, /* doubleLongunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, -2, 0 }, /* doubleLongunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 2 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 2, -1, 1 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 3, -2, 0 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 1, 0, 2 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 2, -1, 1 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 3, -2, 0 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 2 }, /* utf8String */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 2, -1, 1 }, /* utf8String */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 3, -2, 0 }, /* utf8String */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 1, 0, 2 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 2, -1, 1 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 3, -2, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 1, 0, 2 }, /* long */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 2, -1, 1 }, /* long */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 3, -2, 0 }, /* long */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 2 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 2, -1, 1 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 3, -2, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 2 }, /* longunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 2, -1, 1 }, /* longunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 3, -2, 0 }, /* longunsigned */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 1, 0, 2 }, /* long64 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 2, -1, 1 }, /* long64 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 3, -2, 0 }, /* long64 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 1, 0, 2 }, /* long64Unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 2, -1, 1 }, /* long64Unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 3, -2, 0 }, /* long64Unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 1, 0, 2 }, /* enum */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 2, -1, 1 }, /* enum */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 3, -2, 0 }, /* enum */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 1, 0, 2 }, /* float32 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 2, -1, 1 }, /* float32 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 3, -2, 0 }, /* float32 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 1, 0, 2 }, /* float64 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 2, -1, 1 }, /* float64 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 3, -2, 0 }, /* float64 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 1, 0, 2 }, /* dateTime */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 2, -1, 1 }, /* dateTime */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 3, -2, 0 }, /* dateTime */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 1, 0, 2 }, /* date */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 2, -1, 1 }, /* date */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 3, -2, 0 }, /* date */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 1, 0, 2 }, /* time */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 2, -1, 1 }, /* time */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 3, -2, 0 }, /* time */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 1, 0, 2 }, /* date-Time-s */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 2, -1, 1 }, /* date-Time-s */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 3, -2, 0 }, /* date-Time-s */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 1, 0, 2 }, /* oi */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 2, -1, 1 }, /* oi */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 3, -2, 0 }, /* oi */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 1, 0, 2 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 2, -1, 1 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 3, -2, 0 }, /* oad */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 1, 0, 2 }, /* road */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 2, -1, 1 }, /* road */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 3, -2, 0 }, /* road */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 1, 0, 2 }, /* omd */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 2, -1, 1 }, /* omd */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 3, -2, 0 }, /* omd */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 1, 0, 2 }, /* ti */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 2, -1, 1 }, /* ti */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 3, -2, 0 }, /* ti */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 1, 0, 2 }, /* tsa */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 2, -1, 1 }, /* tsa */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 3, -2, 0 }, /* tsa */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 1, 0, 2 }, /* mac */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 2, -1, 1 }, /* mac */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 3, -2, 0 }, /* mac */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 1, 0, 2 }, /* rn */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 2, -1, 1 }, /* rn */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 3, -2, 0 }, /* rn */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 1, 0, 2 }, /* region */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 2, -1, 1 }, /* region */
    { (ASN_TAG_CLASS_CONTEXT | (88 << 2)), 3, -2, 0 }, /* region */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 1, 0, 2 }, /* scalerUnit */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 2, -1, 1 }, /* scalerUnit */
    { (ASN_TAG_CLASS_CONTEXT | (89 << 2)), 3, -2, 0 }, /* scalerUnit */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 1, 0, 2 }, /* rsd */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 2, -1, 1 }, /* rsd */
    { (ASN_TAG_CLASS_CONTEXT | (90 << 2)), 3, -2, 0 }, /* rsd */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 1, 0, 2 }, /* csd */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 2, -1, 1 }, /* csd */
    { (ASN_TAG_CLASS_CONTEXT | (91 << 2)), 3, -2, 0 }, /* csd */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 1, 0, 2 }, /* ms */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 2, -1, 1 }, /* ms */
    { (ASN_TAG_CLASS_CONTEXT | (92 << 2)), 3, -2, 0 }, /* ms */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 1, 0, 2 }, /* sid */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 2, -1, 1 }, /* sid */
    { (ASN_TAG_CLASS_CONTEXT | (93 << 2)), 3, -2, 0 }, /* sid */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 1, 0, 2 }, /* sidMac */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 2, -1, 1 }, /* sidMac */
    { (ASN_TAG_CLASS_CONTEXT | (94 << 2)), 3, -2, 0 }, /* sidMac */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 1, 0, 2 }, /* comdcb */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 2, -1, 1 }, /* comdcb */
    { (ASN_TAG_CLASS_CONTEXT | (95 << 2)), 3, -2, 0 }, /* comdcb */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 1, 0, 2 }, /* rcsd */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 2, -1, 1 }, /* rcsd */
    { (ASN_TAG_CLASS_CONTEXT | (96 << 2)), 3, -2, 0 } /* rcsd */
};
static asn_SEQUENCE_specifics_t asn_SPC_Selector2_specs_1 = {
	sizeof(struct Selector2),
	offsetof(struct Selector2, _asn_ctx),
	asn_MAP_Selector2_tag2el_1,
	121,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Selector2 = {
	"Selector2",
	"Selector2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Selector2_tags_1,
	sizeof(asn_DEF_Selector2_tags_1)
		/sizeof(asn_DEF_Selector2_tags_1[0]), /* 1 */
	asn_DEF_Selector2_tags_1,	/* Same as above */
	sizeof(asn_DEF_Selector2_tags_1)
		/sizeof(asn_DEF_Selector2_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Selector2_1,
	4,	/* Elements count */
	&asn_SPC_Selector2_specs_1	/* Additional specs */
};

