/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_Selector6_H_
#define	_Selector6_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Date-Time-S.h"
#include "TI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MS;

/* Selector6 */
typedef struct Selector6 {
	Date_Time_S_t	 acqStartTimeStartValue;
	Date_Time_S_t	 acqStartTimeEndValue;
	TI_t	 timeInterv;
	struct MS	*meterSet;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Selector6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Selector6;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MS.h"

#endif	/* _Selector6_H_ */
#include <asn_internal.h>
