/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "Server-APDU.h"

static asn_per_constraints_t asn_PER_type_appLayerSvrServer_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_appLayerSvrServer_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.connectResponse),
		(ASN_TAG_CLASS_CONTEXT | (130 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CONNECT_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"connectResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.releaseResponse),
		(ASN_TAG_CLASS_CONTEXT | (131 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RELEASE_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"releaseResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.releaseNotification),
		(ASN_TAG_CLASS_CONTEXT | (132 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RELEASE_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"releaseNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.getResponse),
		(ASN_TAG_CLASS_CONTEXT | (133 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GET_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"getResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.setResponse),
		(ASN_TAG_CLASS_CONTEXT | (134 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SET_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.actionResponse),
		(ASN_TAG_CLASS_CONTEXT | (135 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ACTION_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"actionResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.reportNotification),
		(ASN_TAG_CLASS_CONTEXT | (136 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_REPORT_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.proxyResponse),
		(ASN_TAG_CLASS_CONTEXT | (137 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PROXY_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"proxyResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct appLayerSvrServer, choice.errorResponse),
		(ASN_TAG_CLASS_CONTEXT | (238 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ERROR_Response,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"errorResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_appLayerSvrServer_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (130 << 2)), 0, 0, 0 }, /* connectResponse */
    { (ASN_TAG_CLASS_CONTEXT | (131 << 2)), 1, 0, 0 }, /* releaseResponse */
    { (ASN_TAG_CLASS_CONTEXT | (132 << 2)), 2, 0, 0 }, /* releaseNotification */
    { (ASN_TAG_CLASS_CONTEXT | (133 << 2)), 3, 0, 0 }, /* getResponse */
    { (ASN_TAG_CLASS_CONTEXT | (134 << 2)), 4, 0, 0 }, /* setResponse */
    { (ASN_TAG_CLASS_CONTEXT | (135 << 2)), 5, 0, 0 }, /* actionResponse */
    { (ASN_TAG_CLASS_CONTEXT | (136 << 2)), 6, 0, 0 }, /* reportNotification */
    { (ASN_TAG_CLASS_CONTEXT | (137 << 2)), 7, 0, 0 }, /* proxyResponse */
    { (ASN_TAG_CLASS_CONTEXT | (238 << 2)), 8, 0, 0 } /* errorResponse */
};
static asn_CHOICE_specifics_t asn_SPC_appLayerSvrServer_specs_2 = {
	sizeof(struct appLayerSvrServer),
	offsetof(struct appLayerSvrServer, _asn_ctx),
	offsetof(struct appLayerSvrServer, present),
	sizeof(((struct appLayerSvrServer *)0)->present),
	asn_MAP_appLayerSvrServer_tag2el_2,
	9,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_appLayerSvrServer_2 = {
	"appLayerSvrServer",
	"appLayerSvrServer",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_appLayerSvrServer_constr_2,
	asn_MBR_appLayerSvrServer_2,
	9,	/* Elements count */
	&asn_SPC_appLayerSvrServer_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Server_APDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Server_APDU, appLayerSvrServer),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_appLayerSvrServer_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"appLayerSvrServer"
		},
	{ ATF_POINTER, 2, offsetof(struct Server_APDU, followRpt),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_FollowReport,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"followRpt"
		},
	{ ATF_POINTER, 1, offsetof(struct Server_APDU, timeTag),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TimeTag,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeTag"
		},
};
static const int asn_MAP_Server_APDU_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_Server_APDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Server_APDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* timeTag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* arrayOfObjAttrData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* arrayOfRecAttrData */
    { (ASN_TAG_CLASS_CONTEXT | (130 << 2)), 0, 0, 0 }, /* connectResponse */
    { (ASN_TAG_CLASS_CONTEXT | (131 << 2)), 0, 0, 0 }, /* releaseResponse */
    { (ASN_TAG_CLASS_CONTEXT | (132 << 2)), 0, 0, 0 }, /* releaseNotification */
    { (ASN_TAG_CLASS_CONTEXT | (133 << 2)), 0, 0, 0 }, /* getResponse */
    { (ASN_TAG_CLASS_CONTEXT | (134 << 2)), 0, 0, 0 }, /* setResponse */
    { (ASN_TAG_CLASS_CONTEXT | (135 << 2)), 0, 0, 0 }, /* actionResponse */
    { (ASN_TAG_CLASS_CONTEXT | (136 << 2)), 0, 0, 0 }, /* reportNotification */
    { (ASN_TAG_CLASS_CONTEXT | (137 << 2)), 0, 0, 0 }, /* proxyResponse */
    { (ASN_TAG_CLASS_CONTEXT | (238 << 2)), 0, 0, 0 } /* errorResponse */
};
static asn_SEQUENCE_specifics_t asn_SPC_Server_APDU_specs_1 = {
	sizeof(struct Server_APDU),
	offsetof(struct Server_APDU, _asn_ctx),
	asn_MAP_Server_APDU_tag2el_1,
	12,	/* Count of tags in the map */
	asn_MAP_Server_APDU_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Server_APDU = {
	"Server-APDU",
	"Server-APDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Server_APDU_tags_1,
	sizeof(asn_DEF_Server_APDU_tags_1)
		/sizeof(asn_DEF_Server_APDU_tags_1[0]), /* 1 */
	asn_DEF_Server_APDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Server_APDU_tags_1)
		/sizeof(asn_DEF_Server_APDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Server_APDU_1,
	3,	/* Elements count */
	&asn_SPC_Server_APDU_specs_1	/* Additional specs */
};

