/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "SET-Request.h"

static asn_per_constraints_t asn_PER_type_SET_Request_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_SET_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, choice.setRequestNormal),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetRequestNormal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setRequestNormal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, choice.setRequestNormalList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetRequestNormalList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setRequestNormalList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, choice.setThenGetRequestNormalList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetThenGetRequestNormalList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setThenGetRequestNormalList"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SET_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* setRequestNormal */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* setRequestNormalList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* setThenGetRequestNormalList */
};
static asn_CHOICE_specifics_t asn_SPC_SET_Request_specs_1 = {
	sizeof(struct SET_Request),
	offsetof(struct SET_Request, _asn_ctx),
	offsetof(struct SET_Request, present),
	sizeof(((struct SET_Request *)0)->present),
	asn_MAP_SET_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SET_Request = {
	"SET-Request",
	"SET-Request",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_SET_Request_constr_1,
	asn_MBR_SET_Request_1,
	3,	/* Elements count */
	&asn_SPC_SET_Request_specs_1	/* Additional specs */
};

