/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SET_Response_H_
#define	_SET_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetResponseNormal.h"
#include "SetResponseNormalList.h"
#include "SetThenGetResponseNormalList.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SET_Response_PR {
	SET_Response_PR_NOTHING,	/* No components present */
	SET_Response_PR_setResponseNormal,
	SET_Response_PR_setResponseNormalList,
	SET_Response_PR_setThenGetResponseNormalList
} SET_Response_PR;

/* SET-Response */
typedef struct SET_Response {
	SET_Response_PR present;
	union SET_Response_u {
		SetResponseNormal_t	 setResponseNormal;
		SetResponseNormalList_t	 setResponseNormalList;
		SetThenGetResponseNormalList_t	 setThenGetResponseNormalList;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SET_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SET_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _SET_Response_H_ */
#include <asn_internal.h>
