/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SET_Request_H_
#define	_SET_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetRequestNormal.h"
#include "SetRequestNormalList.h"
#include "SetThenGetRequestNormalList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SET-Request */
typedef struct SET_Request {
	SetRequestNormal_t	 setRequestNormal;
	SetRequestNormalList_t	 setRequestNormalList;
	SetThenGetRequestNormalList_t	 setThenGetRequestNormalList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SET_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SET_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _SET_Request_H_ */
#include <asn_internal.h>
