/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#include "SET-Request.h"

static asn_TYPE_member_t asn_MBR_SET_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, setRequestNormal),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetRequestNormal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setRequestNormal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, setRequestNormalList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetRequestNormalList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setRequestNormalList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SET_Request, setThenGetRequestNormalList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SetThenGetRequestNormalList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setThenGetRequestNormalList"
		},
};
static const ber_tlv_tag_t asn_DEF_SET_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SET_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* setRequestNormal */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* setRequestNormalList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* setThenGetRequestNormalList */
};
static asn_SEQUENCE_specifics_t asn_SPC_SET_Request_specs_1 = {
	sizeof(struct SET_Request),
	offsetof(struct SET_Request, _asn_ctx),
	asn_MAP_SET_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SET_Request = {
	"SET-Request",
	"SET-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SET_Request_tags_1,
	sizeof(asn_DEF_SET_Request_tags_1)
		/sizeof(asn_DEF_SET_Request_tags_1[0]), /* 1 */
	asn_DEF_SET_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_SET_Request_tags_1)
		/sizeof(asn_DEF_SET_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SET_Request_1,
	3,	/* Elements count */
	&asn_SPC_SET_Request_specs_1	/* Additional specs */
};

