/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SetRequestNormalList_H_
#define	_SetRequestNormalList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PIID.h"
#include "ArrayOfOadData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetRequestNormalList */
typedef struct SetRequestNormalList {
	PIID_t	 prioInvID;
	ArrayOfOadData_t	 arrayOfOadData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetRequestNormalList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetRequestNormalList;

#ifdef __cplusplus
}
#endif

#endif	/* _SetRequestNormalList_H_ */
#include <asn_internal.h>
