/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SignatureSecurity_H_
#define	_SignatureSecurity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet-string.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignatureSecurity */
typedef struct SignatureSecurity {
	Octet_string_t	 cipherText2;
	Octet_string_t	 clientSig2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignatureSecurity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignatureSecurity;

#ifdef __cplusplus
}
#endif

#endif	/* _SignatureSecurity_H_ */
#include <asn_internal.h>
