/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_StopBits_H_
#define	_StopBits_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StopBits {
	StopBits_stopbits1	= 1,
	StopBits_stopbits2	= 2
} e_StopBits;

/* StopBits */
typedef long	 StopBits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StopBits;
asn_struct_free_f StopBits_free;
asn_struct_print_f StopBits_print;
asn_constr_check_f StopBits_constraint;
ber_type_decoder_f StopBits_decode_ber;
der_type_encoder_f StopBits_encode_der;
xer_type_decoder_f StopBits_decode_xer;
xer_type_encoder_f StopBits_encode_xer;
per_type_decoder_f StopBits_decode_uper;
per_type_encoder_f StopBits_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StopBits_H_ */
#include <asn_internal.h>
