/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_SymmetrySecurity_H_
#define	_SymmetrySecurity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet-string.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SymmetrySecurity */
typedef struct SymmetrySecurity {
	Octet_string_t	 cipherText1;
	Octet_string_t	 clientSig1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SymmetrySecurity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SymmetrySecurity;

#ifdef __cplusplus
}
#endif

#endif	/* _SymmetrySecurity_H_ */
#include <asn_internal.h>
