/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DLT69845"
 * 	found in "dlt698.45.asn1"
 * 	`asn1c -gen-PER -pdu=all`
 */

#ifndef	_TimeTag_H_
#define	_TimeTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Date-Time-S.h"
#include "TI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeTag */
typedef struct TimeTag {
	Date_Time_S_t	 sendTime;
	TI_t	 allowDelay;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeTag;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeTag_H_ */
#include <asn_internal.h>
